### ISSUE TITLE
Property autocomplete insertion bug

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/lemminx-maven#10]
From https://github.com/AObuchow/lsp4xml-extensions-maven/issues/21

When trying to get autocomplete for properties, I seem to have to type in a character that's part of the completion (eg `{`) to get the autocompletions to appear. However when inserting, the typed in `{` doesn't get removed/accounted for, resulting in incorrect syntax.

For property autocomplete (and possibly other completions), we should take into account what the user has already written and possible replace or modify the existing text using the selected completion.

Demo: https://photos.app.goo.gl/vXVLBM8AdcmD4Qz48

**Comment by AObuchow** [comment]
This might have been fixed in https://github.com/eclipse/lemminx-maven/commit/358597122639cbd5822dbff58b4c44bfd926ce4e but it needs to be verified.

**Comment by mickaelistria** [comment]
I think it's not really a bug. There is no compelling reason to assume a simple `{` is to be interpreted as `${` in general. I tried a bit and didn't spot any oddity with property insertion, so let's close.
