### ISSUE TITLE
Remote artifacts from non-maven central repo's aren't being downloaded on hover

### ISSUE THREAD

**Issue by AObuchow** [eclipse/lemminx-maven#104]
This issue likely affects completion & diagnostics as well.

It seems hover and completion work for non-maven central repo's (eg. soffid.com) that have an index. However, downloading artifacts from these remote repo's does not seem to work.

Evidence of this bug is provided in [this discussion](https://github.com/eclipse/lemminx-maven/issues/57#issuecomment-654989108) where it's pointed out that artifacts which are present in maven central can be downloaded, but not soffid.

This is further proven by https://github.com/eclipse/lemminx-maven/pull/103 which removes soffid from the pom's `<repositories>` but the artifact still gets downloaded (from central).

Thus investigation needs to be done:
- How exactly are remote artifacts being downloaded in LemMinX-Maven (I need to refresh my memory on this...)
- Why are the remote repositories in the `<repositories> `tags not being considered when downloading

**Comment by mickaelistria** [comment]
Is this issue still relevant? Is it still happening with latest release? Do you know some steps to reproduce reliably?

**Comment by AObuchow** [comment]
@mickaelistria I should be able to write a quick test to see if it’s occurring still. I’ll give it a try shortly.

The test would involve finding an artifact in the soffid repo that isn’t on central. Then a hover can be triggered on the artifact and the local .m2 repo can be checked for the next existence of the artifact

**Comment by AObuchow** [comment]
> Is this issue still relevant?

Since m2e doesn't seem to be able to download the artifacts using "update project" (see #149), I don't think it's too relevant.

**Comment by mickaelistria** [comment]
Can you please try reowrking the test with some pom file that uses another Maven repository, where m2e does download the artifact, and then the test would verify wether lemminx-maven behaves as well as m2e?
If it works, then it means the issue is the soffid repo and we can ignore it.

**Comment by AObuchow** [comment]
@mickaelistria unfortunately I don't happen to know another Maven repository that has a valid index that we can test. I'll try to find one when I have a moment, or if someone knows one, please suggest it here.

**Comment by mickaelistria** [comment]
I don't think an index is necessary for this bug/feature; it seems purely about dependency resolution so any repo could fit.

**Comment by AObuchow** [comment]
@mickaelistria you're correct :) I updated the PR accordingly. Seems this is a non-issue and that the soffid repo had some issue.
