### ISSUE TITLE
Duplicate plugin configuration completion items

### ISSUE THREAD

**Issue by AObuchow** [eclipse/lemminx-maven#110]
In the following pom:
```XML
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<modelVersion>4.0.0</modelVersion>
	<groupId>demo</groupId>
	<artifactId>demo</artifactId>
	<version>0.0.1-SNAPSHOT</version>
  
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.1</version>
				<configuration>
				<comp>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
```

I'm getting duplicate plugin configuration proposals. They seem to be exactly the same.

![image](https://user-images.githubusercontent.com/10300119/87172422-37825400-c2a2-11ea-8d57-09f82471e6c6.png)
![image](https://user-images.githubusercontent.com/10300119/87172507-58e34000-c2a2-11ea-9a41-5d83a79d60d1.png)

**Comment by AObuchow** [comment]
Note that this issue occurred once before https://github.com/eclipse/lemminx-maven/issues/53, the fix was https://github.com/eclipse/lemminx-maven/commit/e80b44bd476dffacacffd75e500932750c53062e

**Comment by AObuchow** [comment]
@angelozerr @fbricon  I believe an upstream fix in LemMinX might be best. From what I recall the issue is that the same completion is being added in [`onTagOpen`](https://github.com/eclipse/lemminx-maven/blob/master/lemminx-maven/src/main/java/org/eclipse/lemminx/maven/MavenCompletionParticipant.java#L125) and [`onXMLContent`](https://github.com/eclipse/lemminx-maven/blob/master/lemminx-maven/src/main/java/org/eclipse/lemminx/maven/MavenCompletionParticipant.java#L268).

There's no way to retrieve the completion items already added in the response. However, rather than letting clients check to see if they're adding a duplicate, maybe the upstream/internal container for completion responses should be a set? This would prevent other XML extensions from encountering the same bug in the future.

**Comment by AObuchow** [comment]
@angelozerr @fbricon I found a downstream fix. If my above proposal is desirable however, I can submit a PR.

**Comment by angelozerr** [comment]
> @angelozerr @fbricon I found a downstream fix. If my above proposal is desirable however, I can submit a PR.

I decided not to do that because:

 * each extension could provide the same label but apply completion could be different
 * it could hide bugs with duplicate of completion items

But I'm aware to discuss that, perhaps I'm wrong.

**Comment by AObuchow** [comment]
> > @angelozerr @fbricon I found a downstream fix. If my above proposal is desirable however, I can submit a PR.
> 
> I decided not to do that because:
> 
>     * each extension could provide the same label but apply completion could be different

We could probably make the comparison of completions use all elements from the completion item, including label, documentation, insert text, sort text, etc.... By overriding the `equals` method? Maybe this wouldn't be so easy though if the completion item is coming from LSP4J.

>     * it could hide bugs with duplicate of completion items

I agree with this. Ideally, we shouldn't hide bugs from LemMinX extension developers.

> 
> But I'm aware to discuss that, perhaps I'm wrong.

Maybe better documentation for onTagOpen and onXMLContent is needed to avoid others running into this issue? Something that explicitly warns about providing the same completion in onXMLContent if it's already provided in onTagOpen (as we accidentally did here)?

**Comment by AObuchow** [comment]
Fixed via https://github.com/eclipse/lemminx-maven/commit/bca56c4870545874bbb3ae6681dbb3c622ed3f7b
