### ISSUE TITLE
Hover with multiple properties in the same tag doesn't work

### ISSUE THREAD

**Issue by AObuchow** [eclipse/lemminx-maven#117]
Hovering on "${bar}" in the following pom gives a hover for "foo":
```XML
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<modelVersion>4.0.0</modelVersion>

	<groupId>org.test</groupId>
	<artifactId>test</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>pom</packaging>

	<properties>
		<foo>$</foo>
		<bar>test</bar>
	</properties>
	<contributors>
		<contributor>
			<name>${foo}   ${bar}</name>
		</contributor>
	</contributors>
</project>
```

![image](https://user-images.githubusercontent.com/10300119/88204176-ed419100-cc18-11ea-8433-788a649c83b9.png)

**Comment by AObuchow** [comment]
The above PR shows that this issue isn't occurring in tests. Maybe it's an LSP4E issue?

**Comment by mickaelistria** [comment]
I think it's a mix of some LSP4E issue and a LemMinX-Maven issue: the returned hover doesn't set a range (that's one issue as range should be set to mininize amount of messages transferred), and LSP4E seems to interpret this wrongly.

**Comment by mickaelistria** [comment]
I did debug the thing and LSP4E is correct, and LemMinX-Maven misses to set the Hover range for properties. LemMinX does then set the unset range to the full size of the text node, and LSP4E uses this information to cache the response and reuse it.
So the test should also verify the ranges, and then those should be fixed.

**Comment by AObuchow** [comment]
@mickaelistria thanks for the investigation, I'll fix this then
