### ISSUE TITLE
Old warnings not cleaned up

### ISSUE THREAD

**Issue by akurtakov** [eclipse/lemminx-maven#118]
1. create a workspace while using old lemming maven that had this unrecognized option problem
2. open pom file so warnings are created
3. update lemminx maven to latest
4. warnings stay until manually deleted and lemminx maven no longer recreates them.

**Comment by AObuchow** [comment]
@angelozerr is there a way to clear old warnings in the LemMinX extension API? Once a diagnostic has gone stale it should be removed.

**Comment by mickaelistria** [comment]
I think it's more a LSP4E issue. The warnings should be cleared at least when receiving new diagnostics from the same LS.

**Comment by AObuchow** [comment]
Upstream LSP4E bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=565670

**Comment by mickaelistria** [comment]
Closing as it's an upstream issue.
