### ISSUE TITLE
Can you configure the location of the Lemmix cache?

### ISSUE THREAD

**Issue by willrogers** [eclipse/lemminx-maven#130]
I am trying to do development with Eclipse and Maven. The m2e plugin has apparently caused downloaded almost 1G into `~/.lemminx/index` and exceeded my filesystem quota.

Is there any way to configure where Lemminx puts its cache?

I have tried passing `-Dlemminx.maven.indexDirectory` and `-Dlemminx.workdir` when running Eclipse, but I have not been able to change the behaviour.

I previously opened https://github.com/eclipse/lemminx/issues/851 and we concluded that the ticket was more appropriate here.

**Comment by mickaelistria** [comment]
The `lemminx.maven.indexDirectory` works for the language server, but the Eclipse/m2e integration doesn't seem to forward that property to the LS.
We'd need to improve that with an initializationOption in lemminx-maven, and forward it from m2e to the LS. The fix is then partly in Lemmix-Maven and m2e.

**Comment by mickaelistria** [comment]
I'm thinking we could just move the index to some folder under the local repository by default. Several other maven related tools or plugins do that as well. What do you think?

**Comment by willrogers** [comment]
That would work for me - I use `settings.xml` to move the local Maven repository from my home directory for the same reason.

**Comment by mickaelistria** [comment]
With https://github.com/eclipse/lemminx-maven/commit/d4d79f94c94b49dafd299dfacf62335443b1cda5 , default index location is now under local maven repository, and LemMinX-Maven allows this location to be overriden using `maven.indexLocation` initialization option (under `xml` element).
