### ISSUE TITLE
Maven plugin initialize should not be done in the LemMinx start extension

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lemminx-maven#133]
When XML Language server starts, the MavenPlugin starts and initialize a lot of thing like plexus container, etc although none pom.xml are opened.  As initialize takes some times, it slows the starts of XML Language server.

In other words this initialize https://github.com/eclipse/lemminx-maven/blob/19ed8bb98d79d3fb81c422b72897b1a7e141c518/lemminx-maven/src/main/java/org/eclipse/lemminx/maven/MavenPlugin.java#L122 must be done only if pom.xml is opened and not on the start of the extension.

**Comment by angelozerr** [comment]
@AObuchow  @mickaelistria I would like to work on this issue, are you OK with that?

**Comment by mickaelistria** [comment]
Too late, I'm almost done and am submitting a PR ;)

**Comment by mickaelistria** [comment]
This should now be fixed in 0.2.0-SNAPSHOT
