### ISSUE TITLE
Don't use System.out, System.err or e.printStackTrace

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lemminx-maven#134]
Several code uses 

 * System.out (ex : https://github.com/eclipse/lemminx-maven/search?q=System.out&unscoped_q=System.out), 
 * System.err (ex: https://github.com/eclipse/lemminx-maven/search?q=System.err&unscoped_q=System.err) 
 * e.printStackTrace (ex: https://github.com/eclipse/lemminx-maven/search?q=printStackTrace&unscoped_q=printStackTrace)

If you wish to log something, I suggest that you use Java util logger API like we use for LemMinX (to be consistent).

**Comment by ajo** [comment]
Hi, I've setup logging similar to what you have LemMinX, however test testDownloadArtifactOnHover fails. This test also appears to fail on a fresh pull. Is this related to issue #104, or an issue on my side?

**Comment by AObuchow** [comment]
> Hi, I've setup logging similar to what you have LemMinX, however test testDownloadArtifactOnHover fails. This test also appears to fail on a fresh pull. Is this related to issue #104, or an issue on my side?

I believe it is related to #104 although I’m not certain yet. That test fails for everyone (including myself). When I wrote it, it was passing but perhaps it was only passing cause I had the artifact in my local repo already.

Overall, don’t worry if testDownloadArtifactOnHover is failing as it always seems to fail locally. This should be fixed at some point however, especially as it’s worrisome for newer contributors.

**Comment by mickaelistria** [comment]
Fixed by @ajo with https://github.com/eclipse/lemminx-maven/pull/140 , thanks a lot!
