### ISSUE TITLE
Duplicate dependency completion entries

### ISSUE THREAD

**Issue by fbricon** [eclipse/lemminx-maven#141]
Still trying to get lemminx-maven working in vscode.
Now I'm at a point where I get completion for dependencies, but I see duplicates for some of them:

<img width="848" alt="Screen Shot 2020-09-08 at 7 22 21 PM" src="https://user-images.githubusercontent.com/148698/92510455-2a370680-f20c-11ea-89ff-273d8c77bdeb.png">

**Comment by AObuchow** [comment]
Very happy to see more progress on getting lemminx-maven working in vscode :)

Perhaps the duplicate group id proposal is caused by the local repo lookup & the index lookup? A test case could be made to verify this. I'll try to reproduce in Eclipse when I have a moment today.

**Comment by vrubezhny** [comment]
The issue is fixed with https://github.com/eclipse/lemminx-maven/commit/8c555e48587907b0650e0ca371548d6e5a7eaf06
