### ISSUE TITLE
Invalid .m2 repository directories created when typing in plugin dependency

### ISSUE THREAD

**Issue by AObuchow** [eclipse/lemminx-maven#142]
I was trying to do some testing for https://github.com/eclipse/lemminx-maven/issues/141 and realized while typing in groupId's that I was getting odd completion responses. 

It seems that typing in a groupid will create a directory in the local .m2 repo, even if it's invalid/nonexistent.

To reproduce with the latest m2e snapshot (16.2) installed:
1. Open a pom file
2. In a plugin dependency tag, type in a group id (eg. `some.fake.groupId`)

![image](https://user-images.githubusercontent.com/10300119/92552781-629c0c00-f22f-11ea-8a40-1c77e0e2a576.png)

3. Check the local .m2/repository/ directory and you'll see directories consisting of the previously typed in groupId, each containing a substring of the groupId. Here's part of the output of `tree` in my .m2 repo
```
├── s
│   └── tycho-maven-plugin
│       └── 1.7.0
├── so
│   └── tycho-maven-plugin
│       └── 1.7.0
├── som
│   └── tycho-maven-plugin
│       └── 1.7.0
├── some
│   ├── f
│   │   └── tycho-maven-plugin
│   │       └── 1.7.0
│   ├── fa
│   │   └── tycho-maven-plugin
│   │       └── 1.7.0
│   ├── fak
│   │   └── tycho-maven-plugin
│   │       └── 1.7.0
│   ├── fake
│   │   ├── gro
│   │   │   └── tycho-maven-plugin
│   │   │       └── 1.7.0
│   │   ├── grou
│   │   │   └── tycho-maven-plugin
│   │   │       └── 1.7.0
│   │   ├── group
│   │   │   └── tycho-maven-plugin
│   │   │       └── 1.7.0
│   │   ├── groupI
│   │   │   └── tycho-maven-plugin
│   │   │       └── 1.7.0
│   │   ├── groupId
│   │   │   └── tycho-maven-plugin
│   │   │       └── 1.7.0
│   │   └── tycho-maven-plugin
│   │       └── 1.7.0
│   └── tycho-maven-plugin
│       └── 1.7.0

```

Alternatively, try triggering a completion again as the newly (erroneously) created directories will appear in the local repo proposal

![image](https://user-images.githubusercontent.com/10300119/92552816-7b0c2680-f22f-11ea-9e6d-9d2d9837d635.png)

The pom I was triggering completion on is the following: https://github.com/AObuchow/Eclipse-Spectrum-Theme/blob/master/releng/pom.xml

Note that the pom has 2 extra repositories, maybe this is a contributing factor to the bug.

**Comment by mickaelistria** [comment]
The issue is caused by the fact that when it tries to resolve dependencies (that happens on every keystroke), Maven creates a folder for the dependency even if not existing, in order to mark its last attempt.
I don't know whether maven has some setting to avoid creation of those empty folders.
But we should probably refine the way we return groupId so the folders that contain no artifact are ignored.

**Comment by mickaelistria** [comment]
https://github.com/eclipse/lemminx-maven/pull/143 tries to fix it.
