### ISSUE TITLE
Ctl+Click navigation does not work for managed dependencies

### ISSUE THREAD

**Issue by a1dutch** [eclipse/lemminx-maven#147]
Given a simple spring boot project with the spring-boot-starter-web dependency, CTL + Click on the dependency does not navigate to the pom.  All versions are managed under dependency management in the parent pom.

```
<dependency>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-starter-web</artifactId>
</dependency>
```

**Comment by mickaelistria** [comment]
Fixed with https://github.com/mickaelistria/lemminx-maven/commit/4a54581eac1814113009a3b4201f3c52f8d4a6fe
