### ISSUE TITLE
Huge network traffic

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse/lemminx-maven#152]
Hi

I've just started using `org.eclipse.m2e.lemminx.feature` in my Eclipse. I opened a POM file and I noted that my network monitor started to show a huge download traffic that goes on forever. Note that this happens even if I open the POM with the standard Maven editor, not only when using the lemminx POM editor. I seem to understand that lemminx-maven is downloading Maven artifacts information and indexing such information for code completion and other tooling mechanisms, is that right? Something similar to what the m2e plugin was doing a few years ago by default, and indeed that option is now disabled by default. I see no trace of such a preference configuration for lemminx and I don't understand where it is downloading all that stuff. I'm pretty sure that lemminx-maven is the culprit because if I uninstall it I don't experience this problem anymore.

Isn't there any configuration available for that?

thanks in advance

**Comment by mickaelistria** [comment]
> is that right? 

Mostly yes. Maven Lemminx downloads the Maven Central index, which is a huge file to download, but then provide a *lot* of assistance in editing pom files.

> Isn't there any configuration available for that?

Not at the moment, it would require not only adding it to lemminx-maven (relatively easy, contribution welcome!), but then also tweaking m2e to add such preference in UI and propagate it to lemminx-maven.

**Comment by LorenzoBettini** [comment]
Thanks for your quick answer.

I'm still having many concerns about this behavior. Please correct me if I'm wrong on the following points.

First of all, think of limited data plans. A few gigas are going to be wasted without the user knowing nothing about that.. there's no feedback, I noticed that thanks to my network monitor.

If I close the editor the download stops. If I open it again, the download starts from scratch (in the /tmp folder I seen to understand), what was downloaded is lost.

This behavior is not documented at all. So the user might end up not using the useful features at all since the indeed is never built.

There's no way of disabling such behavior. This might be fine if the user is aware of that and decides not to install lemminx-maven, but, and this scared me most, this feature is part of the standard eclipse Java distribution! And it kicks in even if the user doesn't use the lemminx editor.

Please don't get wrong, I think the project is interesting, though I didn't have a chance to try its features since the index was never built. But at this stage, with no configuration, having this in the standard Java distribution is very dangerous.

**Comment by mickaelistria** [comment]
As mentioned, contributions to fix improve all that are very welcome. But FWIW, it's not at the top of my priority list. I'll prioritize reviews though.

**Comment by LorenzoBettini** [comment]
As mentioned, at least it shouldn't be part of the Java eclipse distribution..

**Comment by mickaelistria** [comment]
You're free to uninstall it ;)

**Comment by LorenzoBettini** [comment]
I have no problem uninstalling it, even more: since a few years I've been using my own Oomph product definitions so that I have well crafted eclipse distributions as I see fit, that's why I had never used lemminx before. I just discovered that because I tried using a plain Java Eclipse distribution.

You still haven't confirmed that the issues I found are real or are just impressions (due to the fact that I never waited for the index to be built), in particular:

- downloading starts when opening a POM with the standard Maven editor, it stops if I close it, and starts from scratch if I open a POM again, discarding what was previously downloaded
- does the standard Maven editor use the lemminx index when built or is the index used only from the generic editor?
- if the Maven editor doesn't use it then this is a waste of resources
- if any of the editors uses the index only when built, then a user should keep the editor open enough hoping that the few gigas have been downloaded, without any feedback?

If these issues are real, and you have no priority in fixing them (which is perfectly fine) then this feature is not production ready, IMHO, at least not enough to be part of any EPP. That's my main concern: the user experience will be very bad, especially for the unexperienced users and it will bring only bad reputation to Eclipse... just my two cents.

So feel free to close this as you see fit, and in case I'll raise an issue to the EPP packages (which will probably be ignored).

**Comment by mickaelistria** [comment]
> downloading starts when opening a POM with the standard Maven editor, it stops if I close it, and starts from scratch if I open a POM again, discarding what was previously downloaded

Yes

> does the standard Maven editor use the lemminx index when built or is the index used only from the generic editor? if the Maven editor doesn't use it then this is a waste of resources

The index is used only with Generic Editor. Maven-LemMinX downloads it a bit too eagerly, when the file is open (Maven-LemMinX participates even when legacy editor is used by "watching" the document).
A patch would also be welcome to improve that.

> if any of the editors uses the index only when built, then a user should keep the editor open enough hoping that the few gigas have been downloaded, without any feedback?

Some feedback is visible in completion proposals "Downloading index for ...".

**Comment by LorenzoBettini** [comment]
Thanks. Some comments inline...

> > downloading starts when opening a POM with the standard Maven editor, it stops if I close it, and starts from scratch if I open a POM again, discarding what was previously downloaded
> 
> Yes
> 

just for curiosity, how long does it take then to have an index ready? For me, after a few minutes nothing was ready... how can one ever enjoy these feature?

> > does the standard Maven editor use the lemminx index when built or is the index used only from the generic editor? if the Maven editor doesn't use it then this is a waste of resources
> 
> The index is used only with Generic Editor. Maven-LemMinX downloads it a bit too eagerly, when the file is open (Maven-LemMinX participates even when legacy editor is used by "watching" the document).
> A patch would also be welcome to improve that.

Then this is a critical issue, and to be honest this should be fixed by the developers. As it is, it's just a waste of resources. I'm not able to contribute currently and I wouldn't know where to look at, but the developers of the project shouldn't have problems in fixing this... hopefully.

Thank you for answering, and I can only confirm that IMHO this should be taken away from the standard EPP packages in this shape. Please let me stress again that from my side I'm not touched by these problems, since I don't have it in my Eclipse installations. But think about new users (if we ever have any...)

**Comment by mickaelistria** [comment]
I'll investigate and try to fix it. I agree that index shouldn't be downloaded without a completion or hover request that makes it useful.

**Comment by mickaelistria** [comment]
First step is https://github.com/eclipse/lemminx-maven/pull/153

**Comment by mickaelistria** [comment]
With #153, the index is not downloaded too eagerly any more, so there is no extra traffic unless necessary/useful.
With #154 , LemMinX-Maven now allows totally disabling index-based assistance with typical LS configuration.
So from lemminx-maven POV, it seems like no further work is needed. It's now up to m2e to leverage those changes.

**Comment by LorenzoBettini** [comment]
Thank you Mickael for your fixes!
Are they already deployed somewhere?
When you talk about "typical LS configuration", how can this be done from Eclipse?

**Comment by mickaelistria** [comment]
> Are they already deployed somewhere?

Yes, in https://repo.eclipse.org/content/repositories/lemminx/org/eclipse/lemminx/lemminx-maven/ as 0.2.0-SNAPSHOT

> When you talk about "typical LS configuration", how can this be done from Eclipse?

There is no UI to customize that. This is intergration material to be leveraged in m2e code (typically introducing a preference), not much handled as it by end-users.
