### ISSUE TITLE
Ctrl-Click on a dependency doesn't open the dependency pom file

### ISSUE THREAD

**Issue by gayanper** [eclipse/lemminx-maven#161]
Ctrl-Click on a dependency doesn't open the dependency pom file. When the mouse is moved over the dependency element with CTRL pressed, the dependency section is highlighted and underlined. But clicking on it doesn't open the dependent pom.xml file.

**Comment by gayanper** [comment]
This works for bom type dependencies which are in managed dependency section.

**Comment by mickaelistria** [comment]
Can you please provide some example? I don't think it's a general issue, but might be the case of the dependency not being found locally.

**Comment by mickaelistria** [comment]
@gayanper any reproducer at hand? If not, I'll have to close the issue.

**Comment by mickaelistria** [comment]
Np feedback, let's close.

**Comment by gayanper** [comment]
This is working in the latest snapshot
