### ISSUE TITLE
Error about "non-resolvable parent pom" if the parent pom is not in central 

### ISSUE THREAD

**Issue by clo-vis** [eclipse/lemminx-maven#168]
Warning: Non-resolvable parent POM for ...: Could not find artifact ... in central (https://repo.maven.apache.org/maven2)

The project can be built normally, within or outside Eclipse (the repository location for the parent is in settings.xml). 

This is the [entry](https://bugs.eclipse.org/bugs/show_bug.cgi?id=568921) in Eclipse Bugzilla.

**Comment by mickaelistria** [comment]
Link to buszilla seems incorrect; can you please share link to the correct entry?
Did you also see https://bugs.eclipse.org/bugs/show_bug.cgi?id=566445 and verified you're running against latest release?

**Comment by clo-vis** [comment]
Now the link is correct.

**Comment by mickaelistria** [comment]
Do you specify specific location for settings file in m2e, or are you leaving empty/default value for settings?
Are those settings in `${user.home}/.m2/settings.xml` ?

With m2e, can you please:
1. close all XML editors
2. Go to Preferences > Langauge Servers > Log
3. enable "Log to file" for the XML Language Server
4. Open one of those files that report the issue
5. look into you `<workspace>/languageServers-log/org.eclipse.wildwebdeveloper.xml.log` file for lines containing `initialize` and share them here?

With that, we'll see whether m2e is passing some incorrect values to this XML Language Server extension, or if the extension is failing at reading proper values...

**Comment by clo-vis** [comment]
{"jsonrpc":"2.0","id":"1","method":"initialize","params":{"processId":19728,"rootPath":"/A:/Workspaces/Java/bar/","rootUri":"file:///A:/Workspaces/Java/bar/","initializationOptions":{"settings":{"xml":{"catalogs":[]}},"maven.globalSettings":"C:\\Users\\clovis\\.m2\\settings.xml"},"capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","delete","rename"],"failureHandling":"undo"},"symbol":{"dynamicRegistration":true},"executeCommand":{"dynamicRegistration":true},"workspaceFolders":true},"textDocument":{"synchronization":{"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"completionItem":{"snippetSupport":true,"documentationFormat":["markdown","plaintext"]}},"hover":{"contentFormat":["markdown","plaintext"]},"signatureHelp":{},"references":{},"documentHighlight":{},"documentSymbol":{"symbolKind":{"valueSet":[18,17,5,14,9,10,22,24,8,1,12,11,20,6,2,3,21,16,19,25,4,7,15,23,26,13]},"hierarchicalDocumentSymbolSupport":true},"formatting":{"dynamicRegistration":true},"rangeFormatting":{},"definition":{"linkSupport":true},"typeDefinition":{"linkSupport":true},"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}},"dynamicRegistration":true},"codeLens":{},"documentLink":{},"colorProvider":{},"rename":{}}},"clientName":"Eclipse IDE","trace":"off"}}

{"jsonrpc":"2.0","id":"1","method":"initialize","params":{"processId":19728,"rootPath":"/A:/Workspaces/Java/bar/","rootUri":"file:///A:/Workspaces/Java/bar/","initializationOptions":{"settings":{"xml":{"catalogs":[]}},"maven.globalSettings":"C:\\Users\\clovis\\.m2\\settings.xml"},"capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","delete","rename"],"failureHandling":"undo"},"symbol":{"dynamicRegistration":true},"executeCommand":{"dynamicRegistration":true},"workspaceFolders":true},"textDocument":{"synchronization":{"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"completionItem":{"snippetSupport":true,"documentationFormat":["markdown","plaintext"]}},"hover":{"contentFormat":["markdown","plaintext"]},"signatureHelp":{},"references":{},"documentHighlight":{},"documentSymbol":{"symbolKind":{"valueSet":[18,17,5,14,9,10,22,24,8,1,12,11,20,6,2,3,21,16,19,25,4,7,15,23,26,13]},"hierarchicalDocumentSymbolSupport":true},"formatting":{"dynamicRegistration":true},"rangeFormatting":{},"definition":{"linkSupport":true},"typeDefinition":{"linkSupport":true},"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}},"dynamicRegistration":true},"codeLens":{},"documentLink":{},"colorProvider":{},"rename":{}}},"clientName":"Eclipse IDE","trace":"off"}}

**Comment by mickaelistria** [comment]
Bouncing back to m2e, the "maven.globalSettings" option seems incorrectly configured, it should be under the `xml` element

**Comment by mickaelistria** [comment]
Let's reopen (although m2e has a part of the issue on its end). On the Bugzilla ticket, you mention that even without defined location, the settings seem ignored?
