### ISSUE TITLE
Silence `XmlPullParserException` when pom syntax is invalid

### ISSUE THREAD

**Issue by datho7561** [eclipse/lemminx-maven#177]
When typing in the `dependencies` section of a pom.xml, `XmlPullParseException`s are generated. Silence these exceptions.

Example to reproduce: type junit at the pipe.
```xml
...
  <dependencies>
    |
  </dependencies>
...
```

Please see https://github.com/microsoft/vscode-maven/issues/47#issuecomment-755108959 for more context.

**Comment by mickaelistria** [comment]
Actually, it's more "whenever typing something that leads to invalid pom file", it's not specific to dependencies.

**Comment by mickaelistria** [comment]
This should be fixed with https://github.com/eclipse/lemminx-maven/commit/07361e1f0df7fd304c2a717bf14887331120e576
