### ISSUE TITLE
NPE when pom syntax is invalid

### ISSUE THREAD

**Issue by datho7561** [eclipse/lemminx-maven#179]
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <artifactId>just-a-pom</artifactId>
  <groupId>com.datho7561</groupId>
  <version>0.1.0</version>
  |
</project>
```

Type something at the pipe, and a NPE is generated.

**Comment by mickaelistria** [comment]
Which version are you using? Can you please paste the full NPE log?
I cannot reproduce it inside Eclipse IDE with m2e+wildwebdeveloper+lemminx-maven.

**Comment by datho7561** [comment]
Sorry about opening this, I can't reproduce it either.

**Comment by angelozerr** [comment]
I have sometimes this error too. The NPE comes from that `e.getCause()` at https://github.com/eclipse/lemminx-maven/blob/07361e1f0df7fd304c2a717bf14887331120e576/lemminx-maven/src/main/java/org/eclipse/lemminx/extensions/maven/searcher/RemoteRepositoryIndexSearcher.java#L100 is null.

The real exception is `java.nio.channels.OverlappingFileLockException`:

![image](https://user-images.githubusercontent.com/1932211/104038893-f4b02300-51d5-11eb-98cc-e110ede49140.png)

**Comment by mickaelistria** [comment]
That's a different bug. Can you please report it separately?
