### ISSUE TITLE
Completion for partially complete artifact names in dependencies

### ISSUE THREAD

**Issue by datho7561** [eclipse/lemminx-maven#180]
Currently, you can add a dependency by opening completion at the `|`, typing the artifact name, then selecting which one you want:
```xml
...
  <dependencies>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-core</artifactId>
      <version>2.11.3</version>
    </dependency>
    |
  </depdenencies>
...
```

It would be helpful if completion could also be provided if you type part of the artifact name, then open completion (at the `|`):
```xml
...
  <dependencies>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-core</artifactId>
      <version>2.11.3</version>
    </dependency>
    junit-|
  </depdenencies>
...
```

It would also be helpful if completion could be provided inside of `<dependencies>` before any other dependencies are declared:
```xml
...
  <dependencies>
    junit-|
  </depdenencies>
...
```

**Comment by mickaelistria** [comment]
All that is working for me with current m2e release.
Which client are you using to test it?

**Comment by datho7561** [comment]
VS Code 1.52.1, using the latest commit of LemMinX

**Comment by mickaelistria** [comment]
See the animated git on README about how things look in Eclipse IDE.
FWIW, my current attention is only focused on Eclipse IDE, but I'd be happy to review incoming PRs to make things work better for VSCode too!

**Comment by datho7561** [comment]
I'll try to debug this.

**Comment by datho7561** [comment]
@Eskibear I created this issue to track the issue that you ran into when integrating lemminx-maven into vscode-maven. I am hoping to have a PR ready for this soon.

**Comment by datho7561** [comment]
@Eskibear Okay, dependency completion should work in VS Code now
