### ISSUE TITLE
Language clients using different user settings format

### ISSUE THREAD

**Issue by rgrunber** [eclipse/lemminx-maven#193]
On the vscode side, a user might set a property such as`"xml.maven.index.skip": true` in their `settings.json` file. This gets transformed to `{ "settings" { "xml" : { "maven" : { "index" : { "skip" : true } } } } }` when sent over in the `initialize` request. Ultimately, the attempt to set the property will fail because LemminxMavenExtension doesn't treat each "dot" of a property as a separate json object. See https://github.com/eclipse/lemminx-maven/blob/master/lemminx-maven/src/main/java/org/eclipse/lemminx/extensions/maven/MavenLemminxExtension.java#L148 

I haven't checked, but I assume that on the Eclipse side, property keys with dots, are not transformed in the same way, so the settings likely work.

Before changing anything, I just want to get a consensus on what the right approach should be. I don't think we can stop the VSCode ecosystem from doing this transformation as it seems to happen at their platform level.

**Comment by rgrunber** [comment]
CC'ing @mickaelistria  @angelozerr @datho7561 for awareness.

**Comment by angelozerr** [comment]
LemMinx Maven should follow the same pattern than other internal extension. In other words it should use GSon to load the settings. This settings must be loaded in the doSave method which is called when a settings or a document is saved.

This doSave is called on the init of the XMLlanguage server. Please see the content model settings which extract validation settings inhttps://github.com/eclipse/lemminx/blob/4e58859d7af1b17032e3aaa3b554ddb9fcbf9730/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/contentmodel/ContentModelPlugin.java#L110

In other words, LemMinx Maven should have a POJO settingsin `org.eclipse.lemminx.extensions.maven.settings` package  like this:

```java
public class MavenRootSettings {

    private MavenSettings maven;

   public MavenSettings getMaven() {
      return maven;
   }
   
  public static MavenRootSettings getMavenRootSettings(Object initializationOptionsSettings) {
     return JSONUtility.toModel(initializationOptionsSettings, MavenRootSettings .class);
   }
}
```

```java
public class MavenSettings {

    private MavenIndexSettings index;

   public MavenIndexSettings getIndex() {
       return index;
   }
}
```

```java
public class MavenIndexSettings [
    private boolean skip;
    
   public boolean isSkip() {
       return skip;
   }
}
```

And after that you could store in the doSave the mavenRootSettings

`mavenRootSettings = MavenRootSettings.getMavenRootSettings(initializationOptionsSettings);`

and use it like this:

`mavenRootSttings.getMaven().getIndex().isSkip();`

or you could move this code in the mavenRootSettings to check the null value.

The only problem that we have is if the settings doesn't follow teh waited structure it crashes the XML Language Server https://github.com/eclipse/lemminx/issues/964 but @datho7561 is studying how to manage this problem.

**Comment by mickaelistria** [comment]
To be honest, building a hierarchy of single field pojos and so on is a bit overkill for this case and is probably less safe and more likely to fail in case of incorrect serialization/deserialization.
I'll probably go for just allowing to read either `maven.index.skip` as a direct child of the configuration element, or to drill down the GSon object if nothing is found. Maybe later, as configuration options get more complex, we'll go for something more structured.

**Comment by angelozerr** [comment]
In WWD you are using XML catalog from LemMinx settings and you do like this.

**Comment by angelozerr** [comment]
IMHO to be consistent with LemMinx settings, LemMinx maven should follow the same pattern.

**Comment by mickaelistria** [comment]
PR welcome ;)

-- 
Mickael Istria
Eclipse IDE <https://www.eclipse.org/downloads/eclipse-packages/>
developer, for Red Hat Developers <https://developers.redhat.com/>
