### ISSUE TITLE
Maven property hover missing?

### ISSUE THREAD

**Issue by AObuchow** [eclipse/lemminx-maven#20]
For some reason, Maven property hover is missing. It was originally added in https://github.com/AObuchow/lsp4xml-extensions-maven/commit/8ab67276e89506e71cb2b78bede86f6294f507cc

**Comment by mickaelistria** [comment]
I think hover overall is failing at the moment. Even when the maven extension returns a good result, this result seems to be overriden by the XSD hover information.

**Comment by AObuchow** [comment]
@mickaelistria I think you may be correct. Although IIRC, the hovers in Lemminx are supposed to be aggregated into a single hover. I wonder why this is happening..

**Comment by AObuchow** [comment]
> I think hover overall is failing at the moment. Even when the maven extension returns a good result, this result seems to be overriden by the XSD hover information.

Maven property hover works in the patch I just submitted, so it might be something else. However, I have experienced the issue you're describing in the past. Maybe it's a timing issue?

**Comment by mickaelistria** [comment]
> Maven property hover works 

Maven properties are not handled by XSD so there is no competition of providers here.
But I'll look a bit more into this issue soon. By the way, the tests about hover for artifactId, goals and so on are actually applied on tag and not on text (this was before your patch on Lemminx got merged IIRC), so this code will need to change and shouldn't conflict wiht XSD any more.

**Comment by AObuchow** [comment]
> > Maven property hover works
> 
> Maven properties are not handled by XSD so there is no competition of providers here.
> But I'll look a bit more into this issue soon. By the way, the tests about hover for artifactId, goals and so on are actually applied on tag and not on text (this was before your patch on Lemminx got merged IIRC), so this code will need to change and shouldn't conflict wiht XSD any more.

Okay good point. I'll create a patch to make them apply when hovering on text as opposed to tags as a workaround to this issue.
