### ISSUE TITLE
Remote plugin repository definition in settings is not used when resolving plugin configurations

### ISSUE THREAD

**Issue by gayanper** [eclipse/lemminx-maven#214]
When resolving plugin descriptors for project plugins, the settings plugin repositories are not used. The following code `org.eclipse.lemminx.extensions.maven.utils.MavenPluginUtils.getContainingPluginDescriptor(IPositionRequest, MavenLemminxExtension)` it uses `org.apache.maven.project.MavenProject.getPluginRepositories()` instead of `org.apache.maven.project.MavenProject.getRemotePluginRepositories()`. The later returns the correct resolved plugin repositories from the settings.

If this is preferred, I can push a patch.

**Comment by mickaelistria** [comment]
Sure a patch would be welcome (ideally with some tests showcasing the issue and validating the fix if possible)

**Comment by mickaelistria** [comment]
@gayanper have you had the opportunity to try latest release? Is this still an issue? Do you still plan to work on it?

**Comment by gayanper** [comment]
@mickaelistria the issue is there, and i have patched my workspace to work with my coperate repository. I didn’t find time to check how i can write test to reproduce this issues to submit the fix

**Comment by mickaelistria** [comment]
OK, please submit a patch without a test if it's too complicated.

**Comment by gayanper** [comment]
Sure i will submit one tomorrow evening.

**Comment by gayanper** [comment]
i will submit the patch in this weekend for sure, bit busy with some JDT work
