### ISSUE TITLE
interation lemminx-maven in emacs'lsp-mode .  maven's settings cannot get then throw NPE

### ISSUE THREAD

**Issue by zcjava** [eclipse/lemminx-maven#227]

**Comment by angelozerr** [comment]
@mickaelistria could you give the default maven settings that lemminx maven could use please.

**Comment by mickaelistria** [comment]
@zcjava Would you like to try submitting a PR for that?

**Comment by zcjava** [comment]
> @zcjava Would you like to try submitting a PR for that?

u donnot have test env by emacs lsp-mode? ok . i try fix it .

**Comment by mickaelistria** [comment]
The project is a plain Maven project, so you can build it with `mvn install`, and import/open it as a regular Maven project. If you're using JDT-LS in Emacs, then I think it should just work by opening the right folder/file and JDT-LS will take care of configuring what's necessary under the hood.

**Comment by zcjava** [comment]
> The project is a plain Maven project, so you can build it with `mvn install`, and import/open it as a regular Maven project. If you're using JDT-LS in Emacs, then I think it should just work by opening the right folder/file and JDT-LS will take care of configuring what's necessary under the hood.

have faster way to debug this project ?

**Comment by mickaelistria** [comment]
Try writing a test case that reproduce you issue, see it fail as expected, fix the code, see the test succeed.

**Comment by zcjava** [comment]
@mickaelistria 
i check source code .
![image](https://user-images.githubusercontent.com/1551382/132623737-3dc1b18c-8c54-4a8f-8268-a4ece0e95fdf.png)
![image](https://user-images.githubusercontent.com/1551382/132623812-61f35de9-3d2e-4c2d-b8fe-13d02b9aa7fe.png)
but is lemminx's source code throw NPE.
i check lsp-mode about lemminx's configurations, whether can set config solve it  by https://emacs-lsp.github.io/lsp-mode/page/lsp-xml/.

**Comment by zcjava** [comment]
![image](https://user-images.githubusercontent.com/1551382/132624976-b8511a41-a450-47ec-b40e-c38b797b171d.png)

**Comment by mickaelistria** [comment]
I had to fix this NPE when implementing a new test https://github.com/eclipse/lemminx-maven/commit/34278ae9f08ea22b7a21555ac11a3b436cc5b832 . So please try latest 0.4.1-SNAPSHOT snapshots or latest master.

**Comment by zcjava** [comment]
> I had to fix this NPE when implementing a new test [34278ae](https://github.com/eclipse/lemminx-maven/commit/34278ae9f08ea22b7a21555ac11a3b436cc5b832) . So please try latest 0.4.1-SNAPSHOT snapshots or latest master.
 initializationoption donot throw NPE,but cause other exception:
![image](https://user-images.githubusercontent.com/1551382/132645936-6fe2f444-6038-4d5c-852a-7d0694c0edf9.png)

**Comment by angelozerr** [comment]
@zcjava it misses in your classpath, the JAR guice-4.2.3-no_aop.jar. I suggest that you add in your classpath all JARs coming from the lemminx-maven-0.4.1-SNAPSHOT-zip-with-dependencies.

**Comment by zcjava** [comment]
> inject

![image](https://user-images.githubusercontent.com/1551382/132657629-17eac13c-84d7-4d9d-96bb-10b8b249e562.png)
![image](https://user-images.githubusercontent.com/1551382/132657755-6fb9cd6a-df95-4f98-993e-8a425f21c2d4.png)
i was do it.  classpath have all jars.

**Comment by zcjava** [comment]
![image](https://user-images.githubusercontent.com/1551382/132660204-a4983ed0-5f32-4b32-81a7-d6244e1c2a46.png)

**Comment by angelozerr** [comment]
Ok great, and now id it working as expected (I mean completion for maven dependency)?

**Comment by zcjava** [comment]
no, the problem is some above exception:
 org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError()
Message: Internal error: java.lang.NoClassDefFoundError: Could not initialize class org.eclipse.sisu.wire.ParameterKeys

**Comment by zcjava** [comment]
![image](https://user-images.githubusercontent.com/1551382/132663567-43bb97a0-1ea5-4e6f-83f1-e62396595fa6.png)

**Comment by zcjava** [comment]
@angelozerr if u have time,please tell me what i need to do fixed this problem.
