### ISSUE TITLE
Add support for assistance using Maven Central Rest API

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/lemminx-maven#232]
Maven Central has a rest API that's more efficient than index in order to search some artifacts.
LemMinX-Maven should adopt it.

**Comment by laeubi** [comment]
@mickaelistria can you point to the class/interface/extensionpoint that has to be implemented/adjusted to support this?

**Comment by laeubi** [comment]
@mickaelistria another question: lets say we add this to lemix, could it be leveraged outside the XML editor (e.g. in maven target locations and `Dependencies > Add`)

**Comment by mickaelistria** [comment]
> can you point to the class/interface/extensionpoint that has to be implemented/adjusted to support this?

There is no Java util class I'm aware of; Central provide an HTTP API https://central.sonatype.org/search/rest-api-guide/ ; maybe @mpiggott can tell more about whether some Java wrapper is available.

>  lets say we add this to lemix, could it be leveraged outside the XML editor (e.g. in maven target locations and Dependencies > Add)

Probably yes, m2e could try to consume some APIs of lemminx-maven. But in practice, if the editor does a good job, `Dependencies > Add` might be better being removed.

**Comment by laeubi** [comment]
> There is no Java util class I'm aware of

I more like to know: Where in lemix one has to add such support?

> But in practice, if the editor does a good job

not sure if one could really give good user experience in a text editor. Never less there might be other places where searching for an artifact might be useful so I wonder if lemix is the right place or if there should be some more generic "maven search API" that is the consumed by m2e and lemix?

**Comment by HannesWell** [comment]
You are referring to the following REST-API, aren't you?
https://central.sonatype.org/search/rest-api-guide/

I find this an interesting topic, but unfortunately don't have the time to work on this right now. If this is still open when I have some time, I can offer to work on this.
But I have to admit I never worked with REST-APIs and just read one/two articles about it and they recommended to use libraries to build the requests.
Do you have some instant recommendations you can share on what to use and where to implement this?

**Comment by laeubi** [comment]
[Unirest](http://kong.github.io/unirest-java/) is a great library to work with "REST-APIs".
That being said, I think for this purpose plain `URL.openConnection()` is sufficient as well.

**Comment by HannesWell** [comment]
> [Unirest](http://kong.github.io/unirest-java/) is a great library to work with "REST-APIs". That being said, I think for this purpose plain `URL.openConnection()` is sufficient as well.

Thanks for that hint.

I also read about the URLConnection/InputStream based approach as the 'manual' way.
But in the end it likely has to be traded-off it a third-library is worth to same some (or maybe more lines of code).

**Comment by mickaelistria** [comment]
> Where in lemix one has to add such support?

Support for Central Search should be in completion participant. If a dedicated API is necessary or useful (I'm not sure it is, the HTTP API can be good enough and there can be deltas between possible usage that makes factorization not so protifable), it would better be a separate library or project IMO. However, for short term, it could be a module in lemminx-maven.
But I'd like to repeat that I'm not sure it's really necessary.

> not sure if one could really give good user experience in a text editor.

That's the at least the goal of lemminx-maven.

> if there should be some more generic "maven search API" that is the consumed by m2e and lemix?

Yes, that would IMO be best. However, maybe the API is simple enough and the consumers diverging enough to just let them use directly the HTTP API without a Java API facade.

> Unirest [...] URL.openConnection() [...]

In the context of lemminx-maven, there is a wide variety of HTTP clients available: `URL.openConnection()` of course, but also `java.net.HttpRequest`, Apache httpclient, okhttp... And also GSON  read JSON or even (un)serizalize Java<->JSON .
The Rest API for Central seems simple enough and I believe that just composing the right request URL, using `HttpRequest` to get the JSON and query the JSON dumbly with GSON (without unserializing to a model, just reading strings) can lead to a good enough solution.

**Comment by laeubi** [comment]
> That's the at least the goal of lemminx-maven.

But given the usual "completion list" I can hardly imagine how this could be done.

Just say we have a `<dependencies>` tag and the cursor is inside it, how it is supposed to work? Should we from now on send every character typed to the rest API to check if it matches an GAV? or only if STRG+SPACE is pressed (do we expect users to know it works that way?). Also browsing a longer list is quite inconvenient with the standard eclipse proposals.

If we assume a full `<dependency>` tag things might become more clear but here again if I'm not quite sure how the G/A/V is that I'm searching for it seems quite clumsy.

As there are already austocompletions, how they work today? Can autocompletion fireup a dedicated dialog to have more convenient search/browsing behavior?

**Comment by mickaelistria** [comment]
> Should we from now on send every character typed to the rest API to check if it matches an GAV?

Same thing is currently happening with index queries.
If a completion session is running and filtering the results is less interesting than re-running the query, yes, the LS re-runs the query.

> do we expect users to know it works that way?

It's also what's happening current with proposals local repo + index.
Users expect completion to suggest best results; so we can assume they'd be happy with it. According to feedback on https://www.youtube.com/watch?v=3W9bvidcO20 , people like the current approach of lemminx-maven, which does lookup artifacts in completion. So it seems like a good workflow to keep relying on.

> Also browsing a longer list is quite inconvenient with the standard eclipse proposals.

Also not different from now.
The completion workflow doesn't rely on the idea of "browsing a longer list". Most users I've seen to type chars to filter the list until their proposal are in the top 5 more or less; this is a bit like a FilteredTree.

> I'm not quite sure how the G/A/V is that I'm searching for it seems quite clumsy.

Also not different from now.
Completion is not a search engine. If you don't know what you want, it's not meant to help you. Completion is meant to save you some time when you have an idea of what you want. eg users would type `spring security` and would get proposal for the `org.springframework.security:spring-security-oauth2-core:5.0.0`.

> As there are already austocompletions, how they work today?

According to "CompletionList#isComplete` (as defined in the LSP spec), the client (LSP4E, VSCode...) will either filter the current results, or will retrigger a full completion query to the language server.

> Can autocompletion fireup a dedicated dialog to have more convenient search/browsing behavior?

Dialogs are totally out of the desired scope of LSP and lemminx-maven. And as mentioned above, a dialog isn't really better than completion list (which acts as a filter). People who don't know what they're looking for are better looking for knowledge in some pages they'll find on the web to make a decision of what they want to use; and then they come back to the editor/IDE and insert the code they want, with some assistance to easily generate the right block of code.

**Comment by laeubi** [comment]
Thanks for the clarifications, so it seems that is something users has to learn that it works that way.
One final question that comes into my mind is: How a user can choose what is queried (e.g. central or nexus API used) will this be automatically choose?

**Comment by mickaelistria** [comment]
> How a user can choose what is queried (e.g. central or nexus API used) will this be automatically choose?

This choice isn't supposed to belong to users directly. LemMinX-Maven must automaticay decide what to query according to the `<repositories>` configured in the project and settings.xml

**Comment by HannesWell** [comment]
It looks like this is resolved by PR #247, isn't it? Thanks a lot @vrubezhny to take care of this!
