### ISSUE TITLE
Maven plugin parameter's description should be displayed on top

### ISSUE THREAD

**Issue by kwin** [eclipse/lemminx-maven#239]
As the Maven plugin parameter's description is the most important information it should be exposed on the top in the hover at https://github.com/eclipse/lemminx-maven/blob/acfdf42aafca2fd07c32890ae8c7d1033b1d2c79/lemminx-maven/src/main/java/org/eclipse/lemminx/extensions/maven/utils/MavenPluginUtils.java#L61.

Compare with https://github.com/eclipse-m2e/m2e-core/issues/477#issuecomment-1004578539.

**Comment by mickaelistria** [comment]
Good idea. Are you willing to submit a PR for that change? It shouldn't be hard to fix.
