### ISSUE TITLE
CPU eaten without stopping for at least an hour

### ISSUE THREAD

**Issue by apupier** [eclipse/lemminx-maven#246]
the XML language Serger is often eatign CPU for a long time on my machine:

```                                                                                                                                                        
 305210 apupier   20   0   12.3g   8.3g  12088 S 354.6  26.7  19:44.38 java                                                                                                                                                                   
 303478 apupier   20   0   12.6g   8.4g  12212 S 350.3  26.9 112:58.03 java  
 ```
 
 I took two stack dump:
[xmlServerlauncher.stack2.txt](https://github.com/eclipse/lemminx/files/7869243/xmlServerlauncher.stack2.txt)
[xmlServerlauncher.stack.txt](https://github.com/eclipse/lemminx/files/7869244/xmlServerlauncher.stack.txt)

Sometimes I even have the UI frozen (but in this case, I was unable to take a Thread dump so far).

I'm using Eclipse Version: 2021-12 (4.22.0) Build id: 20211202-1639 and I think it coming with   Wild Web Developer XML tools	0.13.1.202111081705	org.eclipse.wildwebdeveloper.xml.feature.feature.group	Eclipse Wild Web Developer project

**Comment by apupier** [comment]
reproduced UI freeze and a lot of CPU used. I added a dependency in the source tab of the pom editor of https://github.com/camel-tooling/camel-debug-adapter . The dependency is jaxb-impl

[xmlserver-stackdump.txt](https://github.com/eclipse/lemminx-maven/files/7882661/xmlserver-stackdump.txt)
[eclipse-stackdump.txt](https://github.com/eclipse/lemminx-maven/files/7882662/eclipse-stackdump.txt)

**Comment by mickaelistria** [comment]
@apupier did you have a change to give a try to newer m2e snapshots?

**Comment by digulla** [comment]
Where are the snapshots and how can we test (install) them?

**Comment by mickaelistria** [comment]
The latest snapshots of m2e ( https://github.com/eclipse-m2e/m2e-core#-installation ) should contain a recent version of lemminx-maven.
I'm closing by the way has issue since a potential fix has been available and distributed for about 6 months.
