### ISSUE TITLE
Provide refactoring actions for versions

### ISSUE THREAD

**Issue by laeubi** [eclipse/lemminx-maven#257]
Writing/Maintaining pom.xml files is often boring and cumbersome, especially as there is no real refactoring support (at least not that I know about).

It would be useful if `lemminx-maven ` could support the user if press STRG+1 and a t a `<version>` tag:

- If the version is a fixed one I'd like to get a suggestion to extract the version into a property
- If the version is a fixed one and it matches an existing property I'd like to get a suggestion to replace it with the existing version
- If I have a parent pom I'd like to additional get the option to have the property defined in the parent instead of the current module
- For any option, I'd like to have the choice to do it "batchwise" e.g. replace all fixed versions with the same value, if the property is extracted into the parent, all child poms should be searched and adjusted

**Comment by vrubezhny** [comment]
I believe the most of the suggested code actions are realized when fixing #383
Feel free to create a new issue suggesting the new code actions and other refactorings  to be implemented.
Thanks!
