### ISSUE TITLE
groupId completion returns duplicates

### ISSUE THREAD

**Issue by fbricon** [eclipse/lemminx-maven#261]
Using latest m2e snapshot, try

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>foo</groupId>
  <artifactId>foo</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <dependencies>
  <dependency>
  <groupId>io.quarkus.|</groupId>
  </dependency>
  </dependencies>
</project>
```
You get duplicate groupIds:
<img width="327" alt="Screenshot 2022-02-07 at 10 56 24" src="https://user-images.githubusercontent.com/148698/152765926-f18892c2-3c47-4706-8698-c4f8f83cfe24.png">

**Comment by vrubezhny** [comment]
@fbricon Could you please specify what version of lemminx-maven feature you're on?

**Comment by fbricon** [comment]
I'm using org.eclipse.m2e.lemminx.feature.feature.group 1.18.4.20220127-1634. installed snapshot from this morning. It embeds this:
```
#Generated by Maven
#Thu Jan 27 15:15:29 UTC 2022
groupId=org.eclipse.lemminx
artifactId=lemminx-maven
version=0.5.1
```

**Comment by vrubezhny** [comment]
Could you please give it a try with the latest snapshot version:
![ContentAssist_4_groupId](https://user-images.githubusercontent.com/620781/153044110-ef33603a-ffda-48fe-aa74-cd8991fa69d2.png)

**Comment by fbricon** [comment]
the m2e snapshot hasn't changed. My guess is you're not deduplicating maven central results from the local repo search results

**Comment by vrubezhny** [comment]
Yes, I confirm that I can reproduce the issue. The content assist starts displaying duplications once a user is executed `Run As -> Maven install` command on a project, so the completion items come from both - local and remote repositories.
