### ISSUE TITLE
"Plugin could not be resolved" for core plugins with implicit groupId, and configuration and/or execution

### ISSUE THREAD

**Issue by runeflobakk** [eclipse/lemminx-maven#278]
I observe this warning about non-resolvable plugin:
```
Plugin could not be resolved. Ensure the plugin's groupId, artifactId and version are present.

Additional information: Unable to resolve maven-javadoc-plugin
```
This happens for Maven core plugins without groupId (implicit org.apache.maven.plugins), and including configuration and/or execution element.

Eclipse version: 2021-12 (4.22) Build id: I20211124-1800

M2E - Maven Integration for Eclipse (includes Incubating components) 1.20.0.20220210-1034
M2E - POM Editor (Legacy) using WebTools SourceEditing UI	1.18.3.20220122-2204
M2E - POM Editor using LemMinX language server (includes Incubating components)	1.18.4.20220127-1634

The warning is of type "Language Servers"
<img width="711" alt="javadoc-plugin-warn" src="https://user-images.githubusercontent.com/174823/156205349-a6f9e2c5-ac41-42a2-94da-6eca71b97e73.png">

This issue was initially reported at https://github.com/eclipse-m2e/m2e-core/issues/384

## Minimal reproducing POM:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <artifactId>plugin-resolve-warn</artifactId>
    <groupId>com.github.runeflobakk.eclipse</groupId>
    <version>1-SNAPSHOT</version>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <artifactId>maven-javadoc-plugin</artifactId>
                    <version>3.2.0</version>
                    <configuration></configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>
```
Importing this to a new Maven project in Eclipse reproduces the issue.

Note the empty `<configuration></configuration>`. Although obviously not very sensible with an empty configuration element, it is valid, and it illustrates that this seems to be what triggers the warning. Removing the configuration-element makes the warning disappear. (I can also add any valid elements inside configuration, and the warning persists)

https://user-images.githubusercontent.com/174823/156227229-38bbba61-182d-4600-ab01-022e7a8482d3.mp4

## Example with `<execution>`

I also see this behaviour when alternating between including and excluding an `<execution>` element for a plugin.
I.e. this emits the same warning:
```xml
<plugin>
    <artifactId>maven-failsafe-plugin</artifactId>
    <version>3.0.0-M5</version>
    <executions>
        <execution>
            <goals>
                <goal>integration-test</goal>
                <goal>verify</goal>
            </goals>
            <phase>test</phase>
        </execution>
    </executions>
</plugin>
```

But this does not:
```xml
<plugin>
    <artifactId>maven-failsafe-plugin</artifactId>
    <version>3.0.0-M5</version>
    <executions>
    </executions>
</plugin>
```

Also no warning:
```xml
<plugin>
    <artifactId>maven-failsafe-plugin</artifactId>
    <version>3.0.0-M5</version>
</plugin>
```

**Comment by mickaelistria** [comment]
Submitted https://github.com/eclipse/lemminx-maven/pull/280 which should fix this issue.
