### ISSUE TITLE
Remove aether jars from the distribution to avoid class conflicts

### ISSUE THREAD

**Issue by gayanper** [eclipse/lemminx-maven#291]
The following aether jars are causing class conflicts at runtime when used this extension with vscode-xml

- aether-api
- aether-spi 
- aether-util

**Comment by vrubezhny** [comment]
@gayanper Lemminx-maven depend on  `aether-connector-okhttp` (this is a required dependency),  after  the PR #361 is merged there are no other `aether-*` dependencies are included. 

Could you please try using Lemminx-Maven from [SNAPSHOT](https://repo.eclipse.org/content/repositories/lemminx-snapshots/) at least until the Lemminx-Maven 0.7.2 is released?

**Comment by vrubezhny** [comment]
Closing this issue as fixed after https://github.com/eclipse/lemminx-maven/pull/361 is merged and v.0.7.2 is released.
