### ISSUE TITLE
Autocompletion for directory/file based properties

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/lemminx-maven#292]
See https://github.com/eclipse-m2e/m2e-core/issues/723

**Comment by mickaelistria** [comment]
#293 cover the model elements.
Can you please now try to have this for relevent mojo parameters (with type=File or name ending with `Directory`) ?

**Comment by vrubezhny** [comment]
I expect this issue to be resolved with https://github.com/eclipse/lemminx-maven/commit/3a8259459e9e0fa9eabd3ebaf7222822ef56d93a
