### ISSUE TITLE
Autocompletion is ultra-slow

### ISSUE THREAD

**Issue by laeubi** [eclipse/lemminx-maven#295]
### Inserting standard content
1. Create anew simple maven project
2. press STRG+SPACE inside the empty pom
3. it shows "computing proposals 0%" and nothing happens

At least it should react very fast to the standard tags available at that location, no idea what it is computing there that takes that long

### Inserting variables

4. Now add some content and try e.g. `${p` --> also takes very very long, there should be one very fast completion that at least offers the standard project.version, project.build. ... and so on if it takes to long to compute others.

**Comment by mickaelistria** [comment]
I think the LS is corrupted in that case. Which version of org.eclipse.m2e.editor.lemminx and org.eclipse.wildwebdeveloper.xml do you have ?

**Comment by angelozerr** [comment]
It is the same issue than https://github.com/eclipse/lemminx-maven/issues/444

**Comment by vrubezhny** [comment]
I believe we can close this one in favor of #444 - please follow up.
