### ISSUE TITLE
vscode extension support

### ISSUE THREAD

**Issue by gayanper** [eclipse/lemminx-maven#296]
I was wondering to a create my own vscode extensions by using the lemmnix maven distribution. But i wanted to check before doing that if there could be a chance to add a sub module into this project to release vscode support with each release. 

If the project is ok, I can contribute with the changes.

**Comment by gayanper** [comment]
@mickaelistria WDYT ?

**Comment by akurtakov** [comment]
@rgrunber Aren't you already using lemminx-maven in vscode-java?

**Comment by rgrunber** [comment]
No. There is https://github.com/microsoft/vscode-maven/issues/47 to include this as part of vscode-maven, but that stalled for some time on some issues. Many have been addressed so before creating a new extension it would be good to try and see if we can get it there.

Also https://github.com/angelozerr/vscode-xml-maven/issues/8#issuecomment-1097596010 .

**Comment by gayanper** [comment]
Thanks @rgrunber i will raise it there.
