### ISSUE TITLE
More logging

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/lemminx-maven#300]
We should provide a way to enable more logging in LemMinX-Maven, as many issues found in m2e are hard to debug. Logging should be off by default but easy enough to turn on with some system property for instance. Log should be written to file to not pollute the standard streams that LSP connection may use.
@angelozerr Does lemminx provide some logging strategy to reuse? Or a logging technology to use? Ideally, I'd like to go for `System.Logger`.

**Comment by rgrunber** [comment]
See https://github.com/eclipse/lemminx/blob/b11ed6b6fa20e141ef7bbe28b883b5b51986be13/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/logs/LogHelper.java#L38 . Currently this is set to log to a file using the Java logging API. On `initialize`, the client passes `xml.logs.file`


```
[Trace - 11:42:56 a.m.] Sending request 'initialize - (0)'.
Params: {
    ...
    ...
    "initializationOptions": {
        "settings": {
            "xml": {
                ...
                ...
                "logs": {
                    "client": true,
                    "file": "/home/rgrunber/.config/Code/User/workspaceStorage/ec222aa9662a14fec1c42fa672b05253/redhat.vscode-xml/lemminx.log"
                },
                ... 
                ...
            }
        }
    }
}
```

**Comment by mickaelistria** [comment]
See https://github.com/eclipse/wildwebdeveloper/discussions/974#discussioncomment-4199325 for an example of how LemMinX logging can be harder than it seems.
It's adding complexity that logging this Java-based language server requires unspecified messages via LSP transport and and cannot be set with regular Java system properties (which is properly spec'd and integrated in many many places). Is there a way to simplify LemMinX so it becomes more standard here and make that the Log options are only configured and overridden if they're set in initialization options and using the usual configuration through system properties instead?

**Comment by mickaelistria** [comment]
We've used the current log strategy and settings in Wild Web Developer, and they're good enough at the moment. No need for extra work here.
