### ISSUE TITLE
Move code to root folder?

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/lemminx-maven#311]
The current repo layout introduces 1 extra depth which seems to add no value, and even have negative impact (eg #302 ). Should we just refactor it to move the pom and source folder to the root?
@vrubezhny What do you think?

**Comment by HannesWell** [comment]
Alternatively just the root pom.xml could be added/moved to the repo-root and lemminx-maven could become the only module.
This way more modules could be added in the future, if necessary.

**Comment by mickaelistria** [comment]
Closing in favor of #312
