### ISSUE TITLE
combine.self rejected by validation

### ISSUE THREAD

**Issue by Bananeweizen** [eclipse/lemminx-maven#318]
Using 2.0.0.20220729-1256 org.eclipse.m2e.editor.lemminx, overrides of Maven tags are wrongly rejected by the editor:
```
		<resources combine.self="override">
			<!-- disable the default resource directory -->
		</resources>
```
![image](https://user-images.githubusercontent.com/406876/197960272-42d37c85-fd09-4034-89f9-83d7719ba716.png)
According to https://maven.apache.org/pom.html#advanced_configuration_inheritance this should be fine. Also the Maven build works fine with that code.

**Comment by fbricon** [comment]
Lemminx reports the error strictly as per the Maven schema, which unfortunately doesn't declare combine.self and combine.children as valid attributes, even though they're documented as valid is the very same [schema](https://maven.apache.org/xsd/maven-4.0.0.xsd).

So this is strictly a Lemminx-Maven issue. Probably one of the simplest way to work around it would be to provide a fixed maven schema, declaring the missing attributes,, that would override the real one.

**Comment by fbricon** [comment]
BTW, strictly as per the Maven documentation, only `configuration` children support these extra attributes. So in theory `<resources combine.self="override">` is still illegal. The Maven project should probably fix their doc in that regard.

**Comment by kwin** [comment]
The XSD and also Lemminx is correct. That attribute is only supported on Maven plugin configurations.

**Comment by Bananeweizen** [comment]
Thanks. Then at least I learned something new due to this issue. :)
