### ISSUE TITLE
Navigation / Historical Behaviors have changed (Ctrl-Click, Hover etc.)

### ISSUE THREAD

**Issue by eliasbalasis** [eclipse/lemminx-maven#345]
https://github.com/eclipse-m2e/m2e-core/issues/1184

> Historically, in m2e POM editor when hovering with over a dependency, I could jump to the dependency itself or the place where it is managed.

> In Eclipse 2022-12, I can only jump to the dependency's POM but not to the place where the dependency is managed.

> Also, contrary to historical behavior, if a dependency is present in the Eclipse workspace the POM editor jumps to the workspace file but not anymore.

**Comment by eliasbalasis** [comment]
In Eclipse 2023-03, the problem persists.

**Comment by eliasbalasis** [comment]
Thanks @vrubezhny

More precisely:

Hovering over dependencies that are imported into the Eclipse workspace does not display the pop-up dialog, contrary to historical behavior.

`Ctrl-click` on dependencies that are imported into the Eclipse workspace does not do anything, contrary to historical behavior.

Hovering over external dependencies displays the information but does not jump to the location in Eclipse workspace where the dependency is managed, contrary to historical behavior.

`Ctrl-click` to BOMs imported in the Eclipse workspace does not jump to the relevant Eclipse workspace location, contrary to historical behavior.

I hope this helps you,.

**Comment by eliasbalasis** [comment]
Latest m2e-core with latest LSP4E doesn't seem to be working.

I have built a group of projects that can be used to reproduce any of the cases I am studying.
Clone and import the following Git repositories,
in the order mentioned,
into the workspace of a clean "Eclipse IDE for Enterprise Java and Web Developers 2022-03" installation:
https://github.com/eliasbalasis/eclipse-lemminx-maven-issue-345-root
https://github.com/eliasbalasis/eclipse-lemminx-maven-issue-345-tools
https://github.com/eliasbalasis/eclipse-lemminx-maven-issue-345-project
https://github.com/eliasbalasis/eclipse-lemminx-maven-issue-345-impl

Also, while building these projects I discovered other errors, historically fixed as I recall.
for example: unpredictably not discovering parent POMs without <relativePath> from the Eclipse workspace.

If you manage to load the projects successfully without the unpredictable errors,
look at `<artifactId>eclipse-lemminx-maven-issue-345.tools.retry.springframework.impl.dummy</artifactId>`

Hovering over a local dependencey does nothing, contrary to historical behavior.
`Ctrl-click` over a local dependency does nothing, contrary to historical behavior.
Hovering over an external dependency displays its information but does not jump to the location in Eclipse workspace where the dependency is managed, contrary to historical behavior.

I am getting the feeling this is only the beginning in a chain of problems that we need to fix before users, my teams included, can safely transition to latest versions of M2E without sacrificing any historical behaviors or advantages.

**Comment by vrubezhny** [comment]
@eliasbalasis Thanks for the test projects.

**Comment by mickaelistria** [comment]
> I am getting the feeling this is only the beginning in a chain of problems that we need to fix before users, my teams included, can safely transition to latest versions of Eclipse IDE without sacrificing any historical behaviors or advantages.
Currently we are stuck in 2021-03

Code contributions are highly welcome to lemminx-maven as well as in m2e.

**Comment by eliasbalasis** [comment]
> @eliasbalasis Thanks for the test projects.

Correction, I started with 2023-03, edited

**Comment by eliasbalasis** [comment]
> > I am getting the feeling this is only the beginning in a chain of problems that we need to fix before users, my teams included, can safely transition to latest versions of Eclipse IDE without sacrificing any historical behaviors or advantages.
> > Currently we are stuck in 2021-03
> 
> Code contributions are highly welcome to lemminx-maven as well as in m2e.

I will try to help as much as I can but I will definitely help with testing and discovery.

**Comment by vrubezhny** [comment]
@eliasbalasis I've pushed a PR #388 that includes JUnit tests based on the example projects you have provided. 

 Could you please take a look at [WorkspaceProjectsHyperlinkDetectorTest](https://github.com/eclipse/lemminx-maven/blob/c608ac0034300ec31b23a0037aa09f02fcba9c6d/lemminx-maven/src/test/java/org/eclipse/lemminx/extensions/maven/participants/definition/WorkspaceProjectsHyperlinkDetectorTest.java) and  [WorkspaceProjectsHoverTest](https://github.com/eclipse/lemminx-maven/blob/c608ac0034300ec31b23a0037aa09f02fcba9c6d/lemminx-maven/src/test/java/org/eclipse/lemminx/extensions/maven/participants/hover/WorkspaceProjectsHoverTest.java) ? These two JUnit tests cover some cases for Hyperlinks (by Ctrl-click)) and Hovers for some parent declarations and dependencies (both tests cover identical list of cases, but different actions)

Do you think we need to add some more testcases? Could you suggest any, if needed?

**Comment by eliasbalasis** [comment]
Many thanks for the deep dive.

Test coverage for "Ctrl-Click" and "Hover" is a very welcome addition.
I think you covered enough for now.

I will try to compile a full list of behaviours to consider testing by examining a past version of Eclipse (2021-03) which is known to be working.

In the meantime, I would suggest releasing your changes so that I can actually test them and detect if there are more behaviours to fix.

**Comment by eliasbalasis** [comment]
Has this been released?
Should we probably wait for the next simultaneous Eclipse IDE release to test?

**Comment by vrubezhny** [comment]
@eliasbalasis Released in LemMinX-Maven v.0.8.1 , in order to give it a try you need to update to M2E 2.3.0 (from snapshots - https://download.eclipse.org/technology/m2e/snapshots/latest/) and WWD 1.1.0 (https://download.eclipse.org/wildwebdeveloper/releases/1.1.0/).
