### ISSUE TITLE
Cancel any operation as soon as possible.

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lemminx-maven#358]
Once LSP4E will support cancel support https://github.com/eclipse/lsp4e/pull/431, it should be really nice to support cancel support on lemminx-maven side.

LemMinx support cancel support which stop any operation like XML completion, diagnostics as soon as possible. As vscode provides cancel support, we have a very good performance.

It misses only hover (see https://github.com/eclipse/lemminx/issues/1474)

It is very easy to support cancel support. For instance indefinition you receive the cancel checker https://github.com/eclipse/lemminx-maven/blob/dd3fe65991ad39cbf45c7f689a0a9e49500a4463/lemminx-maven/src/main/java/org/eclipse/lemminx/extensions/maven/participants/definition/MavenDefinitionParticipant.java#L52

and in long process you should call cancelChecker.checkedCanceled(); like in https://github.com/eclipse/lemminx-maven/blob/dd3fe65991ad39cbf45c7f689a0a9e49500a4463/lemminx-maven/src/main/java/org/eclipse/lemminx/extensions/maven/participants/definition/MavenDefinitionParticipant.java#L122

**Comment by angelozerr** [comment]
Please see the PR https://github.com/eclipse/lemminx/pull/1502 which provides the cancel  checker in the Hover API participant.

**Comment by fbricon** [comment]
Shouldn't that issue be closed since #398 was merged?

**Comment by vrubezhny** [comment]
@fbricon I don't think so yet. There is still a number of participants to add cancellation checks or re-visited if they can be cancelled as soon as possible.

**Comment by angelozerr** [comment]
@fbricon please note that it will not work on Eclipse IDE side since LSP client doesn't cancel the request.

**Comment by angelozerr** [comment]
@vrubezhny I think we can close this issue?

**Comment by vrubezhny** [comment]
@angelozerr Yes, I believe the most of cancelling support is added, so we can close this issue.  Thank you!
