### ISSUE TITLE
Property location and jump to location in mouse over popup

### ISSUE THREAD

**Issue by Kiiv** [eclipse/lemminx-maven#370]
In the old pom editor, the popup on a property mouse hover show the declaration location and a link "Jump to location" allowing to jump directly in the pom where the property is declared.

[Screenshot](https://user-images.githubusercontent.com/50696194/149287666-96e2efb0-60d3-4fef-9f5f-da9524b6d393.png)

Is it possible to have the same behaviour ?

**Comment by AObuchow** [comment]
I haven't researched into this much, but the Language Server Protocol (which LemMinX-maven uses) supports the [Goto definition request](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_definition), which could be used for this use case.  LSP4E (Eclipse's implementation of the Language Server Protocol) [seems to support Goto definition](https://github.com/eclipse/lsp4e/blob/a75e770f787769ad43e86034e87362afe6eac20b/org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/definition/DefinitionTest.java). 

So from an LSP-point of view it should be possible.

However, from my understanding, LemMinX-Maven uses the [Maven Project model](https://maven.apache.org/ref/3.2.3/apidocs/src-html/org/apache/maven/project/MavenProject.html#line.1084) in order [to get the project properties](https://github.com/eclipse/lemminx-maven/blob/master/lemminx-maven/src/main/java/org/eclipse/lemminx/extensions/maven/utils/ParticipantUtils.java#L248).

There doesn't seem to be any API for the Maven Project to find out _where_ these properties are declared. So some work would probably have to be done by LemMinX-Maven to manually scan the project and find out where properties are declared. I'm not sure how feasible this is to do (could LemMinX-Maven perform this scan upon loading up the project, and re-scan periodically when the project is modified? Could the [workspace diagnostics request](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_diagnostic) maybe be used for this, and does LSP4E implement it?)

**Comment by mickaelistria** [comment]
definition/F3 works for properties (IIRC you implemented years ago @AObuchow ;).

**Comment by mickaelistria** [comment]
This can be achieved without particular action, we can (and should) simply put links of the form `file://path/to/file#L34,1-L35,3` in the documentation and those should properly open the right file and select the right range. cc @vrubezhny

**Comment by vrubezhny** [comment]
@mickaelistria  I'll take care if no other contributes a fix earlier.
