### ISSUE TITLE
Navigation / Historical Behaviors have changed / Round 2

### ISSUE THREAD

**Issue by eliasbalasis** [eclipse/lemminx-maven#405]
Following #345 and the same test case

https://github.com/eliasbalasis/eclipse-lemminx-maven-issue-345-root
https://github.com/eliasbalasis/eclipse-lemminx-maven-issue-345-tools
https://github.com/eliasbalasis/eclipse-lemminx-maven-issue-345-project
https://github.com/eliasbalasis/eclipse-lemminx-maven-issue-345-impl

on Eclipse IDE 2023-03 with M2E 2.3.0 and WWD 1.1.0 which contain the fix for #345

and after importing into Eclipse IDE the above Maven projects in the order mentioned

look at module `eclipse-lemminx-maven-issue-345.tools.retry.springframework.impl.dummy`

Hovering over `<artifactId>spring-context</artifactId>`
displays description and scope which is a welcome addition
but the origin should be `org.springframework:spring-framework-bom:5.3.3` instead of `org.springframework:spring-context:5.3.3` as per historical behavior.
Ideally, the link should be pointing to the actual origin which is `mygroup:eclipse-lemminx-maven-issue-345.tools.retry.springframework:0.0.1-SNAPSHOT`, more precisely the `org.springframework.boot:spring-boot-dependencies` reference under `<dependencyManagement>` section, but I understand it could be perhaps better to handle this separately.

Hovering over `<artifactId>eclipse-lemminx-maven-issue-345.tools.retry.springframework.interface</artifactId>`
does not display anything contrary to historical behavior.
It should be displaying the standard descriptions with link to `mygroup:eclipse-lemminx-maven-issue-345.tools.retry.springframework:0.0.1-SNAPSHOT` origin, under `<dependencyManagement>` section.

**Comment by vrubezhny** [comment]
@eliasbalasis Thank you for reporting.

**Comment by eliasbalasis** [comment]
In case it helps you.
This is still reproducible with Eclipse 2023-06.

**Comment by Kiiv** [comment]
I can confirm that even https://github.com/eclipse/lemminx-maven/pull/355 does not work for me. I'm still having a link redirecting to the pom artifact itself instead of the pom managing the version.

**Comment by eliasbalasis** [comment]
Thanks @vrubezhny, this is going to make such a significant difference on Maven hierarchies with large depth and complexity.

However, it seems the fix hasn't made it to the release stream yet.

I will wait for a subsequent release containing the fix and then I will test.
