### ISSUE TITLE
Show with progress bar the load of long process

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lemminx-maven#471]
In lemminx maven there are 2 load of long processes which are done in background:

 * load the maven components (plexus container, maven session, etc)
 * load of the local artifacts repository

It should be nice to report as progress bar those loading.

It will require the progress support on lemminx side https://github.com/eclipse/lemminx/issues/1562

**Comment by vrubezhny** [comment]
I really like this idea.

As always - contribution are welcomed!
