### ISSUE TITLE
Plugin configuration validation gives false-positives

### ISSUE THREAD

**Issue by AObuchow** [eclipse/lemminx-maven#48]
There are a number of corner-cases that the [`PluginValidator`](https://github.com/eclipse/lemminx-maven/blob/master/lemminx-maven/src/main/java/org/eclipse/lemminx/maven/PluginValidator.java) is missing. Test's should be added for all these cases.

In my testing, the cases which provide a false positive are:
1. When a plugin's groupId is missing. This gets resolved when the groupId is added. 
Example test case: 
```XML
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.1</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
```
**Note:** the warning does not appear when only the groupId & artifactId is present (for this test case)

2. When certain goals are present (in this example, the `enforce` goal gives a warning, but not the plugin configuration).
Example test case: 
```XML
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-enforcer-plugin</artifactId>
				<version>3.0.0-M3</version>
				<executions>
					<execution>
						<id>enforce-maven</id>
						<goals>
							<goal>enforce</goal>
						</goals>
						<configuration>
							<rules>
								<requireMavenVersion>
									<version>3.0.5</version>
								</requireMavenVersion>
							</rules>
						</configuration>
					</execution>
				</executions>
			</plugin>
```
**Note:** The goal which is giving a warning is giving it's description on hover, which means it was correctly resolved from the plugin descriptor. 
![image](https://user-images.githubusercontent.com/10300119/81215594-93c9ae80-8fa7-11ea-9ead-2fb5432b95bd.png)

3. When a plugin's pom is missing from the `.m2/repository/` folder. This might not be the actual cause, but in the below example case, maven-shade-plugin `3.2.2` & `3.2.1` give plugin configuration errors and aren't able to resolve plugin goals (no goal description on hover). The error is resolved when version `3.2.3` or `2.3` is used. Below is a comparison of the contents of `3.2.2` & `3.2.3`:
```bash
[aobuchow@localhost 3.2.2]$ pwd
/home/aobuchow/.m2/repository/org/apache/maven/plugins/maven-shade-plugin/3.2.2
[aobuchow@localhost 3.2.2]$ ls -la
total 148
drwxr-xr-x. 2 aobuchow aobuchow   4096 May  6 12:28 .
drwxrwxr-x. 6 aobuchow aobuchow   4096 May  6 14:33 ..
-rw-r--r--. 1 aobuchow aobuchow     95 May  6 14:32 m2e-lastUpdated.properties
-rw-r--r--. 1 aobuchow aobuchow 130877 May  6 12:28 maven-shade-plugin-3.2.2.jar
-rw-r--r--. 1 aobuchow aobuchow     40 May  6 12:28 maven-shade-plugin-3.2.2.jar.sha1
-rw-r--r--. 1 aobuchow aobuchow    178 May  6 12:28 _remote.repositories
```
```bash
[aobuchow@localhost 3.2.3]$ pwd
/home/aobuchow/.m2/repository/org/apache/maven/plugins/maven-shade-plugin/3.2.3
[aobuchow@localhost 3.2.3]$ ls -la
total 168
drwxr-xr-x. 2 aobuchow aobuchow   4096 May  6 14:33 .
drwxrwxr-x. 6 aobuchow aobuchow   4096 May  6 14:33 ..
-rw-r--r--. 1 aobuchow aobuchow     95 May  6 14:34 m2e-lastUpdated.properties
-rw-r--r--. 1 aobuchow aobuchow 132252 May  6 14:33 maven-shade-plugin-3.2.3.jar
-rw-r--r--. 1 aobuchow aobuchow     40 May  6 14:33 maven-shade-plugin-3.2.3.jar.sha1
-rw-r--r--. 1 aobuchow aobuchow  10420 May  6 14:33 maven-shade-plugin-3.2.3.pom
-rw-r--r--. 1 aobuchow aobuchow     40 May  6 14:33 maven-shade-plugin-3.2.3.pom.sha1
-rw-r--r--. 1 aobuchow aobuchow    216 May  6 14:33 _remote.repositories
```
To briefly summarise this case: the plugin descriptor isin't being resolved for `maven-shade-plugin 3.2.2` (error on goals & configuration), but is being resolved for `maven-shade-plugin 3.2.3`.
Example test case:
```XML
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-shade-plugin</artifactId>
				<version>3.2.2</version>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
						<configuration>
							<transformers>
								<transformer
									implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
									<mainClass>org.eclipse.dash.licenses.cli.Main</mainClass>
								</transformer>
							</transformers>
							<createDependencyReducedPom>
								false
							</createDependencyReducedPom>
						</configuration>
					</execution>
				</executions>
			</plugin>
```

**Comment by mickaelistria** [comment]
Related m2e issue: https://bugs.eclipse.org/bugs/show_bug.cgi?id=563035

**Comment by AObuchow** [comment]
Case 2 is still an issue. Reopening and going to temporarily disable plugin goal validation, just so that this issue isn't present in M3
