### ISSUE TITLE
Invalid links to line range in external poms in hover

### ISSUE THREAD

**Issue by eliasbalasis** [eclipse/lemminx-maven#505]
Continuing from #405 :

on Eclipse IDE 2023-03
with M2E 2.4.100-20230815-1219
which contains "M2E - POM Editor using LemMinX language serverlemminx" 2.0.5.20230815-1219
which contains "lemminx-maven" 0.10.1
which contains the fix for #405 

https://github.com/eliasbalasis/eclipse-lemminx-maven-issue-345-root
https://github.com/eliasbalasis/eclipse-lemminx-maven-issue-345-tools
https://github.com/eliasbalasis/eclipse-lemminx-maven-issue-345-project
https://github.com/eliasbalasis/eclipse-lemminx-maven-issue-345-impl

and after importing into Eclipse IDE the above Maven projects in the order mentioned

look at module `eclipse-lemminx-maven-issue-345.tools.retry.springframework.impl.dummy`

Hovering over `<artifactId>eclipse-lemminx-maven-issue-345.tools.retry.springframework.interface</artifactId>` now points to the actual oprigin at `mygroup:eclipse-lemminx-maven-issue-345.tools.retry.springframework:0.0.1-SNAPSHOT` under `<dependencyManagement>` section which is an excellent addition.

However,
hovering over `<artifactId>spring-context</artifactId>` the expected origin now displays which is `org.springframework:spring-framework-bom:5.3.3` as per historical behaviour
![image](https://github.com/eclipse/lemminx-maven/assets/1681838/bb1841f1-cae3-4b2c-976c-ff95d892ec08)
but the link does not jump to the displayed origin.
![image](https://github.com/eclipse/lemminx-maven/assets/1681838/293c24aa-3a19-4622-829f-7c719d830895)

Do you think this is something that could be done and hopefully included in Eclipse 2023-09 release ?

Ideally, the link should be pointing to the actual origin which is `mygroup:eclipse-lemminx-maven-issue-345.tools.retry.springframework:0.0.1-SNAPSHOT`, more precisely the `org.springframework.boot:spring-boot-dependencies` reference under `<dependencyManagement>` section, but this could be a new behaviour, a very useful one in my view though.

**Comment by vrubezhny** [comment]
Thanks for reporting, but for me the same link opens a M2E Multipage POM Editor for `~/.m2/repository//org/springframework/spring-framework-bom/5.3.3/spring-framework-bom-5.3.3.pom` file - not in a browser, nor any system text editor... (I can't see what is the editor opened for this link you your case?)
And it does the same if tried with  VSCode-XML+Lemminx-Maven. 

I'll take a look, but at the first look, I think the link is correctly points to the dependency definition made in BOM, doesn't it?

**Comment by mickaelistria** [comment]
> but the link does not jump to the displayed origin.

Where does it jump to? The screenshot doesn't make it clear?
Do I guess it right that it doesn't open the existing file? If so, it could be LSP4E not properly trimming the cursor location from the URI and not opening the right file.

**Comment by eliasbalasis** [comment]
The link jumps to an empty view.

Here is a better screenshot

![image](https://github.com/eclipse/lemminx-maven/assets/1681838/b820ec9c-b211-4d04-8465-ddffe58f3be3)

**Comment by mickaelistria** [comment]
Can you please check in LS logs the exact message that is sent as response to hover on that location?
@vrubezhny I'm trying to figure out whether link is incorrect, or whether it's LSP4E not properly processing the link. Anything other clue we should look at?

**Comment by eliasbalasis** [comment]
[2023-08-21T10:41:28.098330100+01:00] LSP4E_TO_LANGUAGE_SERVER org.eclipse.wildwebdeveloper.xml:
Content-Length: 292



[2023-08-21T10:41:28.098330100+01:00] LSP4E_TO_LANGUAGE_SERVER org.eclipse.wildwebdeveloper.xml:
{"jsonrpc":"2.0","id":"10","method":"textDocument/hover","params":{"textDocument":{"uri":"file:///C:/UPPERLIMIT/PROJECTS/service-bridge/eclipse/workspaces/main/git/eclipse-lemminx-maven-issue-345-tools/modules/retry-springframework-impl-dummy/pom.xml"},"position":{"line":34,"character":20}}}

[2023-08-21T10:41:28.130562300+01:00] LANGUAGE_SERVER_TO_LSP4E org.eclipse.wildwebdeveloper.xml:
{"jsonrpc":"2.0","id":"10","result":{"contents":{"kind":"markdown","value":"**Spring Framework (Bill of Materials)**\r\n\r\nSpring Framework (Bill of Materials)\r\n\r\n**The managed version is 5.3.3.** **The artifact is managed in [org.springframework:spring-framework-bom:5.3.3](file:/C:/UPPERLIMIT/PROJECTS/service-bridge/eclipse/workspaces/main/maven/.m2/repository/org/springframework/spring-framework-bom/5.3.3/spring-framework-bom-5.3.3.pom#L63,22-L63,22 \"org.springframework:spring-framework-bom:5.3.3\")**\r\n\r\n**The managed scope is: \"compile\"**"},"range":{"start":{"line":34,"character":15},"end":{"line":34,"character":29}}}}

**Comment by mickaelistria** [comment]
`[org.springframework:spring-framework-bom:5.3.3](file:/C:/UPPERLIMIT/PROJECTS/service-bridge/eclipse/workspaces/main/maven/.m2/repository/org/springframework/spring-framework-bom/5.3.3/spring-framework-bom-5.3.3.pom#L63,22-L63,22 \"org.springframework:spring-framework-bom:5.3.3\")` is indeed incorrect link syntax, the `  \"org.springframework:spring-framework-bom:5.3.3\")` seems erroneously added as a suffix.

**Comment by mickaelistria** [comment]
Would you be interested in trying to submit a PR that fixes this issue?

**Comment by eliasbalasis** [comment]
I wish I could.
I wouldn't even know where to start though and it would be a steep learning curve to effectively cover before the next Eclipse release.

Going forward I will consider.

**Comment by vrubezhny** [comment]
@mickaelistria Probably you're right and the link "suffix" looks wrong. I just wanted to note that this bug doesn't happen to me on Fedora. So, probably it's an Windows related issue

**Comment by vrubezhny** [comment]
> `[org.springframework:spring-framework-bom:5.3.3](file:/C:/UPPERLIMIT/PROJECTS/service-bridge/eclipse/workspaces/main/maven/.m2/repository/org/springframework/spring-framework-bom/5.3.3/spring-framework-bom-5.3.3.pom#L63,22-L63,22 \"org.springframework:spring-framework-bom:5.3.3\")` is indeed incorrect link syntax, the ` \"org.springframework:spring-framework-bom:5.3.3\")` seems erroneously added as a suffix.

Isn't the ` \"org.springframework:spring-framework-bom:5.3.3\"` part (between the URL address part and closing `)` bracket a "Link Title" ( or a tooltip which is to be normally shown in browser when you hover the mouse over the link)?

[Example Link with Title](https://github.com/eclipse/lemminx-maven/issues/505 "Example Title"):
![Screenshot from 2023-08-26 18-41-37](https://github.com/eclipse/lemminx-maven/assets/620781/83ceb06f-02ba-4e3b-a4df-4e8942d6b9a1)

**Comment by eliasbalasis** [comment]
It this related to "lemminx-maven" ?

If yes, then why is the problem not reproducible with version 0.9.0 ?

If no, what could be the responsible component ?

**Comment by mickaelistria** [comment]
Is this link title tooltip syntax standard in markdown?

**Comment by mickaelistria** [comment]
OK. Could it be wikitext failing to render such constructs?

**Comment by vrubezhny** [comment]
> OK. Could it be wikitext failing to render such constructs?

It's rendered successfully on Linux. Maybe different versions behave differently on different platforms?
But I'm not sure if wikitext is used to open a link when you clink it in Hover window - imho, it's edge/ie browser problem (Not sure though)

**Comment by mickaelistria** [comment]
I'm not sure either. However, wouldn't it be worth removing link title if it's problematic in some cases?

**Comment by eliasbalasis** [comment]
Probably yes, or simply ignore the new markdown option?
