### ISSUE TITLE
Duplicate plugin configuration completion's

### ISSUE THREAD

**Issue by AObuchow** [eclipse/lemminx-maven#53]
When triggering a completion within a `<configuration>...</configuration>` tag, it seems that duplicate completion's can exist. The description of these duplicate completions seems exactly the same, so we can probably filter them out by comparing existing completion descriptions (for plugin configuration).

See below for a comparison of the completion descriptions:
![image](https://user-images.githubusercontent.com/10300119/81604144-72990180-939d-11ea-9b27-d50e9bb4395d.png)
![image](https://user-images.githubusercontent.com/10300119/81604185-817fb400-939d-11ea-93d2-6d410ba0a32c.png)

**Comment by mickaelistria** [comment]
how come the same paramters are added twice in first place?

**Comment by AObuchow** [comment]
> how come the same paramters are added twice in first place?

Not sure yet, I have to look into the code when I have a moment. A test for this should also be easy to implement.
