### ISSUE TITLE
exclude m2e lifecyclemapping from plugin validation

### ISSUE THREAD

**Issue by Bananeweizen** [eclipse/lemminx-maven#536]
When using m2e lifecycle mapping exclusions in the pom.xml to get rid of M2E warnings in Eclipse, then you are doomed to now get a plugin descriptor validation warning instead for the lifecycle mapping entry. Can we please hardcode this GAV to not raise that validation error? 
![grafik](https://github.com/eclipse/lemminx-maven/assets/406876/a0fa5f61-e925-4354-b478-fd4fce9d3e2f)

**Comment by mickaelistria** [comment]
I don't think we'll start to hardcode stuff for m2e in lemminx. I think m2e should maybe consider publishing this mojo, so some edition assistance could then be provided.
If you want to avoid this warning, you can also try decarating a plugin/execution node with `<?m2e ignore?>`

**Comment by eliasbalasis** [comment]
I have been successfully using <?m2e?> for quite a few few years.
The "lifecycle-mapping" plugin has been deprecated and the recommended practice is <?m2e?> since M2E 1.7
see https://eclipse.dev/m2e/documentation/release-notes-17.html#new-syntax-for-specifying-lifecycle-mapping-metadata

**Comment by Bananeweizen** [comment]
While I have been using the lifecycle mapping pseudo plugin since many years and in dozens of projects. I've not been aware of the XML syntax up until Mickael suggested it. I guess that it might be the same for many others because the quick fixes all add the lifecycle mapping. So maybe we need to improve the quickfixes in m2e instead?
