### ISSUE TITLE
Navigation / Historical Behaviors have changed / Round 3 / Umbrella

### ISSUE THREAD

**Issue by eliasbalasis** [eclipse/lemminx-maven#539]
In Eclipse 2023-09 with latest m2e 2.4.0 installed which still carries lemminx-maven 0.10.1 but seems to be fixing #513

the value of Maven properties, inherited from ancestor artifacts not in the workspace but still resolvable, are not displayed while hovering.

This is contrary to historical behavior.

However, only when the ancestor artifact is imported into the Eclipse workspace the value is displayed.

Also, in Eclipse 2023-12, carrying lemminx-maven 0.11.0 and m2e 2.5.0 the XML Language Server times out when hovering over any dependency or Maven property and Ctrl+Click has stopped working again.
`Could not get hover region due to timeout after 1000 milliseconds`
`Could not get hover information due to timeout after 1000 milliseconds`

It seems m2e 2.5.0 has broken all the previously fixed behaviors.

On top of this, I am discovering the following:
1.
Java properties are not resolved in the Maven editor (for example "fille.separator")
This is contrary to historical behavior.
2.
When Maven properties, inherited from ancestor modules are changing in the Eclipse workspace the value is not updated when hovering over a reference to the changed Maven property.
This is contrary to historical behavior.

**Comment by mickaelistria** [comment]
Can you please open 1 separate ticket for each issue, with a title focusing on the actual issue, ie "value of property not shown when property is defined out of workspace" ?

**Comment by eliasbalasis** [comment]
This relates to #540

**Comment by eliasbalasis** [comment]
This relates to #541

**Comment by eliasbalasis** [comment]
This relates to #542

**Comment by eliasbalasis** [comment]
This relates to #543

**Comment by mickaelistria** [comment]
Thanks!

**Comment by eliasbalasis** [comment]
This relates to #546
