### ISSUE TITLE
properties not resolved after changing POM and rebuilding

### ISSUE THREAD

**Issue by eliasbalasis** [eclipse/lemminx-maven#541]
In Eclipse 2023-09 with latest m2e 2.4.0 installed which still carries lemminx-maven 0.10.1 but seems to be fixing #513:

When making changes to a POM a build is automatically triggered but the Maven properties sometimes are not resolved and wrong values are assigned in *.properties files

I guess this could be either a lemminx issue or a M2E Core one, but given #540 I am guessing it could be lemminx related.

**Comment by mickaelistria** [comment]
I think this one is more about m2e: lemminx doesn't execute the mojos, it doesn't generate the *.properties file, it just reads poms to display info in editor. So if the issue happens in the build more than in the editor, it's most likely m2e.
