### ISSUE TITLE
Navigation behaviors have stopped working on m2e 2.5.0

### ISSUE THREAD

**Issue by eliasbalasis** [eclipse/lemminx-maven#543]
Also, in Eclipse 2023-12, carrying lemminx-maven 0.11.0 and m2e 2.5.0 the XML Language Server times out when hovering over any dependency or Maven property and Ctrl+Click has stopped working again.

`Could not get hover region due to timeout after 1000 milliseconds`
`Could not get hover information due to timeout after 1000 milliseconds`

It seems m2e 2.5.0 has broken all the previously fixed behaviors.

**Comment by mickaelistria** [comment]
This case is working for me. However, please keep in mind that lemminx-maven actually reads and resolve the poms and that operation can take long time. So if you try it soon after it starts, LemMinX-Maven may timeout while a few seconds later, it would return a proper result.
LemMinX-Maven should be improved to better inform of its "readiness". for example by showing a notification when it's queried but not ready yet.

**Comment by eliasbalasis** [comment]
I will try to test more thoroughly and let you know.

**Comment by eliasbalasis** [comment]
False alarm.

I can now confirm the behaviors haven't changed in Eclipse 2023-12.
