### ISSUE TITLE
Add completion support for parent

### ISSUE THREAD

**Issue by gayanper** [eclipse/lemminx-maven#56]
Add completion support for `<parent>`, this should provide at least the same list of dependencies which is shown under the dependency tag. if possible we can improve this by only showing dependencies which have the packaging type of pom.

**Comment by AObuchow** [comment]
Sorry I'm not entirely sure I understand yet.
Could you explain a bit further (why are the parent's dependencies being needed in the <parent> tag?).

Alternatively, you could give a short example of a parent pom, a child pom and where the completion was triggered, and what types of completions should show up.
Thanks @gayanper

**Comment by AObuchow** [comment]
Are you suggesting a child pom might want to inherit from the pom of one of its dependencies?

**Comment by gayanper** [comment]
This is when you use different parent poms out of your module area, one example would be the spring-boot parent pom.
https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-parent

**Comment by AObuchow** [comment]
If you find a pom.xml file that's using the spring boot starter parent (from the module area) that I can see, that would help a lot (so I can understand a bit more and create a test case).

It doesn't have to be the spring boot starter, anything that represents this use case is fine.

Sorry, I'm not really familiar with this use case but I want to support it.

**Comment by gayanper** [comment]
[pom.zip](https://github.com/eclipse/lemminx-maven/files/4732400/pom.zip)
Here is a sample pom file, try to complete the parent codinates. When i tried this in vscode the completions happens, does vscode use lemminx-maven ?

**Comment by mickaelistria** [comment]
Can you please explicit from this example, where is the cursor when you're asking for completion, and what are the expected results, and what do you get (and also what does VSCode return) ?

**Comment by gayanper** [comment]
After fixing the windows paths issues by @AObuchow seems like this is working now.

**Comment by gayanper** [comment]
Sorry i closed the wrong issue

**Comment by gayanper** [comment]
@mickaelistria vs code doesn’t work. I check again. It shows some suggestions it finds in the pom it self for parent cordinate. My expectations are that it should work as it works for dependency cordinate auto completions.

**Comment by gayanper** [comment]
@mickaelistria vscode works, sorry earlier something was wrong. But now in vscode when I try it actually completion artifactIds and versions in the parent as in the dependency section.

**Comment by mickaelistria** [comment]
Can you please clarify what you mean by "works"? Which VSCode plugin do you
use to get Maven support? What file are you completing, at which offset and
what result do you get?

**Comment by mickaelistria** [comment]
Closing by lack of feedback.
