### ISSUE TITLE
Complete -S in versions with -SNAPSHOT

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/lemminx-maven#60]
When in a `<version>...</version>` node, unless some smarter completion is available, completion should suggest -SNAPSHOT for -S and other prefixes.

**Comment by AObuchow** [comment]
I guess we should also add completion for `RELEASE` and `LATEST`?

**Comment by mickaelistria** [comment]
Maybe, but RELEASE and LATEST are occasional conventions, while SNAPSHOT is really part of Maven standard.

**Comment by AObuchow** [comment]
Alright, then RELEASE and LATEST could be possible future enhancements, part of another bug.

**Comment by AObuchow** [comment]
Fixed in https://github.com/eclipse/lemminx-maven/commit/358597122639cbd5822dbff58b4c44bfd926ce4e
