### ISSUE TITLE
Missing completion for updated properties defined in parent pom

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/lemminx-maven#63]
Properties defined in parent pom are missing in completion

**Comment by mickaelistria** [comment]
So I managed to refine the issue:
Steps to reproduce
* have a parent and a child, parent has some property p2
* Complete some `${` in child, see `${p1}` as proposal, good
* Change the parent to replace `p1` by `p2`, save
* Get to child and retry completion
EXPECTED: `${p2}` and not `${p1}` in completion, GOT the opposite
* modify child to force a model rebuild,
* retry completion
EXPECTED: `${p2}` and not `${p1}` in completion, GOT the opposite

It seems like the model doesn't react to change in parent.

**Comment by mickaelistria** [comment]
I think this is related to ModelCache (that we should avoid using for "working copies")

**Comment by mickaelistria** [comment]
https://github.com/eclipse/lemminx-maven/pull/67 tries to fix this

**Comment by AObuchow** [comment]
related upstream Maven issue: https://issues.apache.org/jira/browse/MNG-6911

**Comment by AObuchow** [comment]
This should most likely be fixed now that https://github.com/eclipse/lemminx-maven/commit/1c4ef722411b9cab12ab105ce5a348bb8ad5d21e is merged. @mickaelistria do you think I should close this (despite the upstream issue still being opened)?.

**Comment by mickaelistria** [comment]
Yes, let's close. We'll think about improving it when we receive a notification from Maven issue.
