### ISSUE TITLE
MavenDefinitionParticipant is missing test coverage.

### ISSUE THREAD

**Issue by AObuchow** [eclipse/lemminx-maven#68]
There are many cases supported by MavenDefinitionParticipant that aren't being tested for.
https://github.com/eclipse/lemminx-maven/pull/66 shows how to test definitions.

**Comment by pauldpong** [comment]
Just wanted to verify that I am looking in the correct direction. MavenDefintionParticipant also handles the definitions of tags such as the GAV correct?

**Comment by mickaelistria** [comment]
I suggest we close this.
Usually, it's not profitable to add tests after the fact. It's better to add tests when developing a feature or when noticing a bug, but not after the feature is shipped as long as there is no known issue.
