### ISSUE TITLE
Unit tests failing on windows

### ISSUE THREAD

**Issue by gayanper** [eclipse/lemminx-maven#69]
Following is the test execution done in a azure pipeline with windows-latest vm.
[lemmix-windows-tests.txt](https://github.com/eclipse/lemminx-maven/files/4671457/lemmix-windows-tests.txt)

@AObuchow Shall we try to add a window github workflow as well ?

**Comment by AObuchow** [comment]
@gayanper thank you very much for testing this and sending back the results.

I'm willing to try and setup a github workflow for windows CI, @mickaelistria any thoughts?

This week I'm also going to be setting up my Windows machine for testing and development of LemMinX-Maven.

**Comment by AObuchow** [comment]
@gayanper if you want, feel free to test that the tests are now passing on your Windows system and let me know :)

**Comment by gayanper** [comment]
Seem my results @AObuchow 3 tests fails on my windows slave https://dev.azure.com/gayanper/lemminx-maven/_build/results?buildId=121&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=ce18b30f-11b8-5f1e-8fbd-391708956df7&l=10876

**Comment by AObuchow** [comment]
@gayanper thanks Gayan, that seems like a OS dependant issue in the test case. Will submti a fix.

**Comment by gayanper** [comment]
@AObuchow May be you can setup a windows builds for github as well. Its pretty easy, you only need to change the image type that you want to use.

**Comment by AObuchow** [comment]
@gayanper yes I'd like too. today is the last day to get lemminx-maven into m2e for simrel however so this will have to wait unfortunately. I just submitted a PR to fix the issue you encountered on your Azure CI instance, if you're able to, let me know if this fixes the issue.
