### ISSUE TITLE
submodule and relativePath completion for filesystem

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/lemminx-maven#7]
From https://github.com/AObuchow/lsp4xml-extensions-maven/issues/68

> Currently, it looks like submodule and parent completion can only repeat what's already set in the pom. However, those should try to look at local filesystem to provide completion.

> Agreed, I believe this is what m2e is already currently doing and we should replicate the existing behavior.

> Should the strategy for this completion improvement be something like:
> * Look above/below in the filesystem hierarchy (above for parent, below for submodule)
> *  If a pom.xml is encountered in the filesystem search, parse it (using MavenXpp3Reader or MavenProjectBuilder) to get GAV and add it to the completion
>
> This opens a question for parent completion - when should we stop searching the filesystem? At the user's home directory (might not work well on Windows)? Should we have a depth constant which limits the search depth?

> For the parent, I think we should stick to only pom in parent the parent folder if there is any.
in the relative paths, we can complete any string with the filesystem content (ie, complete target/output/ with the files and folders in this path).

Difficulty: *...
Value: ***.

**Comment by AObuchow** [comment]
Fixed via https://github.com/eclipse/lemminx-maven/commit/a709cf4a411517e501b27a2990517946438a4db1, thanks Mickael!
