### ISSUE TITLE
Missing completion for plugin parameters

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/lemminx-maven#75]
Using
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>demo</groupId>
  <artifactId>demo</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <build>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.1</version>
        <configuration>
          <release>14</release>
          <compilerArgs>
            <arg>--enable-preview</arg>
          </compilerArgs>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
```
no code completion is available for plugin parameters. However, hovering seems to work.

**Comment by AObuchow** [comment]
I’ll try to come up with a test for it quickly and hopefully a fix as well.

Might be worth trying to see if reverting https://github.com/eclipse/lemminx-maven/commit/e80b44bd476dffacacffd75e500932750c53062e fixes the issue.

**Comment by AObuchow** [comment]
By plugin parameters, I image you mean configuration completions, such as `<release></release>`?

**Comment by mickaelistria** [comment]
False alarm, it actually works (I was probably testing an older commit for lemminx-maven by mistake). Sorry for the noise.
However, feel free to merge the test, the most tests, the better.

**Comment by AObuchow** [comment]
Ah okay I see, no worries.

Sure I'll slightly modify the test just to rename it and reference this issue in a comment.
