### ISSUE TITLE
Nominate Mickael Istria as a committer

### ISSUE THREAD

**Issue by AObuchow** [eclipse/lemminx-maven#85]
For obvious reasons (see [this repo's commit log ](https://github.com/eclipse/lemminx-maven/commits/master)  as well as [the old repo's commit log](https://github.com/AObuchow/lsp4xml-extensions-maven/commits/master)), @mickaelistria should be nominated as a LemMinX committer so that he can easily merge patches as well as have access to the LemMinX Jenkins CI instance.

**Comment by fbricon** [comment]
@AObuchow [any committer](https://www.eclipse.org/projects/handbook/#elections) can start the [nomination process](https://projects.eclipse.org/projects/technology.lemminx/nominate/CM).

**Comment by AObuchow** [comment]
@fbricon yes you’re right :) I made this bug more as a personal reminder to myself, more than anything hahah

**Comment by AObuchow** [comment]
The nomination process has begun: https://projects.eclipse.org/projects/technology.lemminx/elections/election-mickael-istria-committer-eclipse-lemminx

**Comment by AObuchow** [comment]
@fbricon @xorye @NikolasKomonen could you please submit your votes when you all have a moment please? :)

**Comment by AObuchow** [comment]
The nomination process has finished :)
