### ISSUE TITLE
Maven property hover doesn't always work

### ISSUE THREAD

**Issue by AObuchow** [eclipse/lemminx-maven#97]
Using Eclipse IDE 4.16 on the following pom, I'm unable to get maven property hover working.

```XML
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<modelVersion>4.0.0</modelVersion>

	<groupId>org.test</groupId>
	<artifactId>test</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>pom</packaging>

	<properties>
		<myProperty>$</myProperty>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.${myProperty}.${project.version}</groupId>
		</dependency>
	</dependencies>
</project>
```

 I am however able to get ctrl + click to open the property declaration, and I can see that the property is getting resolved by the maven project builder (as a diagnostic is created stating `'dependencies.dependency.groupId' for org.$.0.0.1-SNAPSHOT:null:jar with value 'org.$.0.0.1-SNAPSHOT' does not match a valid id pattern.`).

**Comment by AObuchow** [comment]
Running `SimpleModelTest.testPropertyHover`, I can see that the kind "plaintext" is used when the type is MarkupContent:
```
Hover [
  contents = Either [
    left = null
    right = MarkupContent [
    kind = "plaintext" <----------------------
    value = "Property: myProperty\n\nValue: $\n\n"
  ]
  ]
  range = Range [
    start = Position [
      line = 15
      character = 12
    ]
    end = Position [
      line = 15
      character = 48
    ]
  ]
]
```

Maybe this could be causing the bug @mickaelistria ?

**Comment by mickaelistria** [comment]
I don't think the "kind" is supposed to cause a bug, and if it does, it's probably more a bug in LSP4E. Did you try debugging m2e and LSP4E to verify whether the "kind" cause the bug?

**Comment by AObuchow** [comment]
@mickaelistria I agree that if this causes an issue, it should be a LSP4E bug.

I haven't tried debugging m2e + LSP4E to verify this yet. I was thinking of just building the lemminx-maven jar locally and testing it in m2e to see if changing the "kind" fixes the issue.

Maybe debugging LSP4E in a child Eclipse that has lemminx-maven (from the 4.16 release) in the target platform would be better, to see if the LSP hover gets triggered and chooses not to display the hover?

**Comment by AObuchow** [comment]
Just tested with the m2e 1.16.1 snapshot and the bug is still present. Going to debug LSP4E

**Comment by AObuchow** [comment]
> Just tested with the m2e 1.16.1 snapshot and the bug is still present. Going to debug LSP4E

On second thought: I'm unable to get any hovers working right now. I also noticed the maven index is updating... I'll wait for it to complete. The actual bug might be affecting all hovers.

**Comment by AObuchow** [comment]
Turns out m2e & Wild Web Developer XML were out of sync with using the latest version of LemMinX which had new hover API. Now that I've upgraded to the latest Wild Web Developer snapshot & m2e snapshot, this issue is resolved.
